# PYTHONPATH=. uv run torchrun --nproc_per_node=8 training_script/tokenizer/train_tokenizer_ddp_atari.py
import os
from pathlib import Path
import torch
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.utils.data import DataLoader, DistributedSampler
from torch.optim import AdamW
from tqdm import tqdm
import wandb
import numpy as np

from tokenizer.model.encoder_decoder import CausalTokenizer
from tokenizer.losses import MSELoss
from tokenizer.patchify_mask import Patchifier, MaskGenerator

# ---------------------------------------------------------------------------
class AtariConfig:
    # Dataset paths
    data_dir = Path("data/atari/raw")
    
    # Model architecture (Optimized for 64x64)
    resize = (64, 64)       
    patch_size = 8         
    clip_length = 64
    input_dim = 3 * patch_size * patch_size
    embed_dim = 256
    latent_dim = 256
    num_heads = 8           
    num_layers = 8         
    
    # Training (Scale batch size for 16GB V100)
    batch_size = 32        # Per-GPU batch size
    num_workers = 4
    lr = 1e-4
    weight_decay = 1e-2
    max_epochs = 100         
    log_interval = 10
    
    # Visualization
    visualize_interval = 10
    num_frames_to_viz = 4
    
    # Paths
    ckpt_dir = Path("checkpoints/atari/tokenizer_v3")
    viz_dir = Path("visualizations/atari/tokenizer_v3")
    
    # WandB
    project = "dreamer4-atari"
    entity = "hiroki-kimiwada-"
    run_name = "breakout-tokenizer-100k"

# ---------------------------------------------------------------------------
class AtariTensorDataset(torch.utils.data.Dataset):
    """Loads .pt tensors generated by the Atari collection script."""
    def __init__(self, data_dir, clip_length=8, patch_size=16, resize=(64, 64)):
        self.data_dir = Path(data_dir)
        self.clip_length = clip_length
        self.patch_size = patch_size
        self.resize = resize
        
        self.frame_paths = sorted(list(self.data_dir.glob("frame_*.pt")))
        if not self.frame_paths:
            raise RuntimeError(f"No .pt frames found in {data_dir}")
            
        self.patchifier = Patchifier(patch_size=patch_size)
        self.masker = MaskGenerator(mask_prob_range=(0.0, 0.0), per_frame_sampling=True)
        
    def __len__(self):
        return len(self.frame_paths) - self.clip_length + 1
        
    def __getitem__(self, idx):
        frames = []
        for i in range(idx, idx + self.clip_length):
            # Load (C, H, W) and normalize to [0, 1]
            f = torch.load(self.frame_paths[i], map_location="cpu").float() / 255.0
            frames.append(f)
        
        frames = torch.stack(frames) # (T, 3, H, W)
        patches = self.patchifier(frames) # (T, N, D)
        T, N, D = patches.shape
        mask = self.masker(T=T, N=N, device=torch.device("cpu"))
        
        return {"patch_tokens": patches, "mask": mask}

# ---------------------------------------------------------------------------
def setup_ddp():
    dist.init_process_group(backend="nccl")
    rank = dist.get_rank()
    local_rank = int(os.environ["LOCAL_RANK"])
    world_size = dist.get_world_size()
    torch.cuda.set_device(local_rank)
    return rank, local_rank, world_size

def cleanup_ddp():
    dist.destroy_process_group()

@torch.no_grad()
def visualize_reconstruction(model, batch, cfg, epoch, device):
    """Visualize side-by-side reconstruction."""
    cfg.viz_dir.mkdir(parents=True, exist_ok=True)
    model.eval()
    
    patches = batch["patch_tokens"].to(device)
    mask = batch["mask"].to(device)
    recon = model(patches, mask)
    
    patchifier = Patchifier(patch_size=cfg.patch_size)
    H, W = cfg.resize
    num_frames = min(cfg.num_frames_to_viz, patches.shape[1])
    frames_to_viz = np.linspace(0, patches.shape[1] - 1, num_frames, dtype=int)
    images = []

    for t in frames_to_viz:
        orig_frame = patchifier.unpatchify(patches[0, t:t+1], (H, W), cfg.patch_size)[0].clamp(0, 1)
        recon_frame = patchifier.unpatchify(recon[0, t:t+1], (H, W), cfg.patch_size)[0].clamp(0, 1)
        
        orig_np = (orig_frame.cpu().permute(1, 2, 0).numpy() * 255).astype(np.uint8)
        recon_np = (recon_frame.cpu().permute(1, 2, 0).numpy() * 255).astype(np.uint8)
        images.append(np.concatenate([orig_np, recon_np], axis=1))

    final_img = np.concatenate(images, axis=0)
    wandb.log({"visualization": wandb.Image(final_img, caption=f"Epoch {epoch}")})
    model.train()

def save_best_checkpoint(model, optimizer, epoch, loss, cfg, best_loss):
    if loss >= best_loss:
        return best_loss
    cfg.ckpt_dir.mkdir(parents=True, exist_ok=True)
    best_path = cfg.ckpt_dir / "best_model.pt"
    torch.save({
        "model_state": model.module.state_dict(),
        "optimizer_state": optimizer.state_dict(),
        "epoch": epoch,
        "loss": loss,
    }, best_path)
    print(f"✓ [Best Model] Epoch {epoch} | Loss: {loss:.6f} → {best_path}")
    return loss

# ---------------------------------------------------------------------------
def main():
    cfg = AtariConfig()
    rank, local_rank, world_size = setup_ddp()
    device = torch.device(f"cuda:{local_rank}")
    is_main = rank == 0

    if is_main:
        wandb.init(project=cfg.project, entity=cfg.entity, name=cfg.run_name, config=vars(cfg))

    dataset = AtariTensorDataset(cfg.data_dir, cfg.clip_length, cfg.patch_size, cfg.resize)
    sampler = DistributedSampler(dataset, num_replicas=world_size, rank=rank, shuffle=True)
    loader = DataLoader(dataset, batch_size=cfg.batch_size, sampler=sampler, num_workers=cfg.num_workers, pin_memory=True)

    model = CausalTokenizer(
        input_dim=cfg.input_dim, embed_dim=cfg.embed_dim, num_heads=cfg.num_heads,
        num_layers=cfg.num_layers, latent_dim=cfg.latent_dim, use_checkpoint=True
    ).to(device)
    model = DDP(model, device_ids=[local_rank], output_device=local_rank)

    criterion = MSELoss().to(device)
    optimizer = AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

    best_loss = float("inf")

    for epoch in range(1, cfg.max_epochs + 1):
        sampler.set_epoch(epoch)
        model.train()
        epoch_loss = 0.0

        if is_main:
            pbar = tqdm(loader, desc=f"Epoch {epoch}/{cfg.max_epochs}")
        else:
            pbar = loader

        for batch in pbar:
            patches = batch["patch_tokens"].to(device)
            mask = batch["mask"].to(device)

            optimizer.zero_grad()
            recon = model(patches, mask)
            loss = criterion(recon, patches, None)
            if isinstance(loss, tuple): loss = loss[0]
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            epoch_loss += loss.item()

        # Sync loss across GPUs
        avg_loss = torch.tensor(epoch_loss / len(loader), device=device)
        dist.all_reduce(avg_loss, op=dist.ReduceOp.SUM)
        avg_loss = (avg_loss / world_size).item()

        if is_main:
            print(f"[Epoch {epoch}] Avg Loss: {avg_loss:.6f}")
            wandb.log({"epoch/avg_loss": avg_loss, "epoch/num": epoch})
            
            best_loss = save_best_checkpoint(model, optimizer, epoch, avg_loss, cfg, best_loss)

            if epoch % cfg.visualize_interval == 0:
                viz_batch = next(iter(loader))
                visualize_reconstruction(model, viz_batch, cfg, epoch, device)

    if is_main:
        wandb.finish()
    cleanup_ddp()

if __name__ == "__main__":
    main()