"""Build the final ~30-minute talk: Dreamer 4 framed around world models: what they are, where the field stood in 2024-25, and what
makes Dreamer 4 special. Reuses the slide functions of the deep dive (deck_slides.py) in a new order, with new framing slides.
Run: python3 build_final.py     (NO_MOVIE=1 OUT=/tmp/x.pptx python3 build_final.py for the poster-only PDF source)"""
from deck_common import *
from deck_slides import *

# ------------------------------------------------------------------ new slides for the final talk
def f_title():
    s = prs.slides.add_slide(BLANK); state["n"] += 1; state["titles"].append("Dreamer 4: a world model good enough to train an agent in (title)")
    bg = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, W, H); bg.fill.solid(); bg.fill.fore_color.rgb = NAVY; bg.line.fill.background()
    strip_w, strip_h = Inches(5.433), Inches(2.5); sx = W - strip_w
    for i, (f, pre, anchor) in enumerate([("frame_imag_treechop.jpg", (0, 0, 634, 356), "top"), ("frame_diamond_dreamer.jpg", None, "top"), ("frame_realworld_soar1.jpg", None, "center")]):
        im = Image.open(A + f).convert("RGB")
        if pre: im = im.crop(pre)
        tw, th = im.width, int(im.width * strip_h / strip_w)
        if th > im.height: th = im.height; tw = int(im.height * strip_w / strip_h)
        l = (im.width - tw) // 2; t = 0 if anchor == "top" else (im.height - th) // 2
        im.crop((l, t, l + tw, t + th)).save(A + f"title_strip_{i}.jpg", quality=88)
        s.shapes.add_picture(A + f"title_strip_{i}.jpg", sx, i * strip_h, width=strip_w, height=strip_h)
    kicker(s, Inches(0.8), Inches(1.4), Inches(6), "World models  ·  arXiv 2509.24527", color=SKY, size=11)
    add_text(s, Inches(0.75), Inches(1.8), Inches(6.8), Inches(1.3), "Dreamer 4", size=64, bold=True, color=WHITE)
    add_text(s, Inches(0.8), Inches(2.95), Inches(6.6), Inches(1.5), ["A world model good enough", "to train an agent in"], size=26, color=WHITE, line_spacing=1.1)
    hline(s, Inches(0.85), Inches(4.5), Inches(0.9), color=SKY, pt=1.5)
    add_text(s, Inches(0.8), Inches(4.7), Inches(6.6), Inches(1.2), ["Training Agents Inside of Scalable World Models", "Hafner*, Yan*, Lillicrap (Google DeepMind), September 2025"], size=14.5, color=RGBColor(0xC9, 0xD3, 0xE6), line_spacing=1.2)
    add_text(s, Inches(0.8), Inches(6.55), Inches(6.6), Inches(0.4), "Presenter ____________     Date ____________     ~30 min + discussion", size=11.5, color=RGBColor(0x8F, 0x9B, 0xB8))
    caption(s, Inches(0.8), Inches(6.95), Inches(6.6), "Right, all generated by the Dreamer 4 world model: an imagined rollout, a human playing inside the model, and the robot-arm model.", size=9)
    notes(s, "This talk is about world models, and about one paper that changed what we can expect from them: Dreamer 4, by Danijar Hafner, Wilson Yan and Tim Lillicrap at Google DeepMind, September 2025. "
             "The one-line version: world models have become impressive to look at; Dreamer 4 is the first that is accurate and fast enough to train an agent in, and it proves it by learning to find diamonds in Minecraft from offline video alone. "
             "The three frames on the right are all generated by the model, not recorded from the game.")
    return s

def f_thesis():
    s = new_slide("The thesis in one slide", "Three statements and three numbers")
    numbered(s, Inches(0.6), Inches(1.65), Inches(7.9), [
        ("World models became media.", "In 2024–25, Genie, Oasis, Lucid-v1 and GameNGen showed real-time, playable video worlds. They were judged by how they look and feel; whether an agent could learn in them was not asked."),
        ("An agent needs more than looks.", "To train in a model, the mechanics must be right (menus, crafting, tools), it must run fast enough for millions of rollouts, and it must stay stable over long horizons. The playable models failed the first test; the agent-side models (Dreamer 1–3) passed it only at 64×64 pixels with privileged state."),
        ("Dreamer 4 is the first to do both.", "Humans solve 14 of 16 interaction tasks inside it in real time, and an agent trained only inside it, from 2,541 h of offline video, reaches diamonds. No environment interaction at any point.")], size=15.5, gap=0.32, num_w=0.65)
    note(s, Inches(8.9), Inches(1.65), Inches(4.0), Inches(3.6), "Three numbers to remember", [
        "**14 / 16**: interaction tasks human testers solve inside the model, live, at 21 FPS (Table 1; best prior Minecraft model: 5 / 16)",
        "**21 FPS on one H100**, with a 9.6 s context and four sampling steps per frame; the same design at 64 steps ran at 0.8 FPS (Table 2)",
        "**29 % · 0.7 %**: iron pickaxe and diamond success from offline video only; a Gemma-3 VLA on the same data: 11 % · 0 %, plain BC: 0.6 % · 0 % (Table 7)"], size=13)
    caption(s, Inches(0.6), Inches(6.35), Inches(12.2), "Route: Part 1, what a world model is and where the field stood; Part 2, six things Dreamer 4 does differently; Part 3, the evidence; Part 4, where it stands and what to take away.")
    notes(s, "Three statements carry the whole talk. One: world models became a media category, judged visually. Two: an agent needs mechanics, speed and long-horizon stability, and no single model had all three. "
             "Three: Dreamer 4 has them, and the proof is two experiments: humans playing inside the model, and an agent that learned inside the model succeeding in the real game. "
             "The three numbers on the right are the ones to remember if nothing else sticks.")
    return s

def f_landscape():
    s = new_slide("Two families of world models, and where Dreamer 4 sits", "2019–2025: models an agent trains inside vs. models a human plays inside (numbers from Table 1 and the vendors' announcements)")
    fit_picture(s, jpeg(A + "diag_landscape.png", max_w=2400, q=90), Inches(0.4), Inches(1.5), Inches(12.5), Inches(4.42))
    add_bullets(s, Inches(0.6), Inches(6.0), Inches(12.2), Inches(0.95), [
        "Two yardsticks: agent-side models are judged by the agent's return, media-side models by how the video looks. Dreamer 4 is held to both, plus a third: does an agent trained *only* inside it succeed in the real game?",
        "The direct baselines are the playable Minecraft models (Table 1); Genie 3 is the closest in ambition but exposes no comparable action space, so the paper cannot compare against it (§4.2)"], size=12, space=3)
    notes(s, "A map of the field. Top row: world models built for agents, from the first Dreamer in 2019 to DreamerV3 and DIAMOND: fast, but small images and often privileged state; nobody would want to play inside them. "
             "Middle row: the 2024–25 wave of world models as media (Genie, GameNGen, Oasis, Lucid-v1, Genie 2, MineWorld, Genie 3): high-resolution, real-time, made for people to play, judged by how they look. The Minecraft ones are the direct baselines in the paper, and none of them survives a crafting menu. "
             "The blue note is the other way to combine the two: SIMA 2 trains inside Genie 3's worlds, but the agent stays outside the model. Dreamer 4, bottom, is the first model that sits in both rows: humans play it, the agent trains in it, and the agent is then tested in the real game.")
    return s

def f_six_things():
    s = new_slide("What makes Dreamer 4 special: six design decisions", "Each maps to a slide in this part; the phase of the recipe it belongs to is in brackets")
    numbered(s, Inches(0.6), Inches(1.6), Inches(8.0), [
        ("Latents, not pixels.", "A causal tokenizer compresses each frame to 256 continuous tokens; simulation and RL happen in latent space, pixels are only decoded for people [phase 1]"),
        ("Shortcut forcing: diffusion quality in four steps.", "Diffusion forcing + shortcut models, with x-prediction and an x-space loss, so long rollouts stay sharp and fast [phase 1]"),
        ("An architecture tuned for 21 FPS on one GPU.", "Space attention in most layers, causal time attention every 4th, grouped-query attention, registers; 9.6 s of context in real time [phase 1]"),
        ("The agent lives inside the world model.", "Agent tokens with one-way attention read the simulator's state; policy, reward and value are small heads on the same transformer [phase 2]"),
        ("Imagination training, offline, with PMPO.", "The transformer is frozen; policy and value heads learn from imagined rollouts scored by the learned reward head, anchored to the BC prior [phase 3]"),
        ("Action semantics from few labels.", "Unlabeled video gets a learned 'no action' embedding; ~100 h of labels suffice and the actions transfer to worlds seen only unlabeled [phase 1]")], size=14, gap=0.24, num_w=0.65)
    note(s, Inches(9.0), Inches(1.65), Inches(3.9), Inches(4.9), "The recipe (Algorithm 1)", [
        "**Phase 1 · World-model pretraining:** tokenizer (masked autoencoding), then the dynamics model with shortcut forcing on all 2,541 h, labeled or not",
        "**Phase 2 · Agent fine-tuning:** add agent tokens, policy and reward heads; behavioural cloning with multi-token prediction while the dynamics loss keeps running",
        "**Phase 3 · Imagination training:** freeze the transformer; train policy and value heads by RL on rollouts inside the model",
        "One block-causal transformer throughout; the agent is a few heads on top of the simulator."], size=12.5)
    notes(s, "The recipe on the right is three phases: pretrain the world model, fine-tune it into an agent by imitation, then train the policy by RL inside the model. "
             "The six items on the left are what the paper does differently at each step, and they are the structure of this part: one slide per item, with the shortcut-forcing item getting the three primers it needs.")
    return s

def f_takeaways():
    s = new_slide("What makes Dreamer 4 special, in one slide")
    tk = [("The first world model good enough to train in", "Humans solve 14 of 16 interaction tasks inside it in real time; an agent trained only inside it reaches diamonds from offline video."),
          ("Real-time diffusion is the enabling trick", "Shortcut forcing (4 steps), x-prediction with an x-space loss and time attention every 4th layer: 21 FPS on one GPU with 9.6 s of context."),
          ("One transformer, three roles", "Tokenizer, simulator and agent share the block-causal design; the agent reads the simulator through one-way attention and cannot bias it."),
          ("Imagination adds what imitation cannot", "Most of the gain over BC is the world-model representation; RL inside the model adds the rest where data is thin: iron pickaxe 16.9 → 29 %, diamonds 0 → 0.7 %."),
          ("Video is the prior, labels are cheap", "About 100 h of action labels on top of thousands of unlabeled hours suffice; action semantics transfer to worlds seen only as video."),
          ("What is still open", "9.6 s of memory, a frozen simulator the policy could exploit, thin statistics on the headline number, and no code or weights.")]
    columns(s, Inches(1.55), Inches(2.6), tk[:3], size=14.5, head_size=15.5, head_h=0.72)
    columns(s, Inches(4.4), Inches(2.6), tk[3:], start=4, size=14.5, head_size=15.5, head_h=0.72)
    notes(s, "Six things to take home, in the order of the talk: the claim, the trick that makes it possible, the architecture, what RL adds, what the data story is, and what remains open.")
    return s

# ------------------------------------------------------------------ the talk
f_title()
s = s_video(); notes(s, "Play the official video here (2:55), or the embedded ten-second teaser on the right if the room has no internet. The video is Figure 1 of the paper in motion: imagined rollouts decoded for visualisation, building up to the headline claim. "
                        "Say it explicitly: what you see there is generated by the world model, not recorded gameplay. The four uncut 60-minute evaluation episodes on the same channel show the trained agent in the real game (linked on the results slide). "
                        "YouTube does not allow downloading, so the deck only links to the video; the teaser and the 60 project-page clips are archived in dreamer4_resources/media/.")
f_thesis()

section("World models", "What they are, what the 2024–25 wave delivered, and what an agent needs from one", 1)
titled(s_why_wm, "What a world model is, and what 'learning in imagination' means")
f_landscape()
titled(s_what_made_hard, "What an agent needs from a world model, and why that was hard", "Three requirements that pulled in different directions")
titled(s_tech_tree, "The test: twelve milestones, three tool gates, ~24,000 actions", "2,541 h of human gameplay video, no environment interaction; where each agent falls off (Tables 7 and 8)")

section("What makes Dreamer 4 special", "Six design decisions: latents, shortcut forcing, a fast architecture, the agent inside, offline RL, cheap labels", 2)
f_six_things()
titled(s_wm_design, "1 · One transformer, two roles: causal tokenizer + dynamics model")
titled(s_primer_flow, "2 · Primer 1 of 3 · Flow matching: one dial from noise to image")
titled(s_primer_df, "2 · Primer 2 of 3 · Diffusion forcing: a noise level per frame")
titled(s_primer_shortcut, "2 · Primer 3 of 3 · Shortcut models: learning to take big steps")
titled(s_shortcut_forcing, "2 · Shortcut forcing: the training objective")
titled(s_xpred, "2 · Why x-prediction matters for autoregressive world models")
titled(s_efficient, "3 · Architecture choices that buy speed without losing quality")
titled(s_agent_tokens, "4 · From world model to agent: agent tokens & heads")
titled(s_pmpo, "5 · Imagination training with PMPO")
titled(s_label_efficiency, "6 · Unlabeled video: how many action labels are needed?")

section("Does it hold up?", "Humans inside the model, diamonds from offline data, and where the gains come from", 3)
s_table1()
s_interaction_frames()
titled(s_diamond_results, "Diamonds from offline experience: the results")
s_ablations()

section("Where it stands", "Genie 3, the caveats, and what to take away", 4)
titled(s_genie3_2, "Genie 3 and Dreamer 4: agent outside vs. agent inside the model")
s_critical()
f_takeaways()
s_questions()
s_references()

state["part"] = "Appendix"
s_testbed(); s_predecessors(); s_three_phases(); s_algorithm1_a(); s_algorithm1_b(); s_stack_1(); s_stack_2(); s_wm_compare_2(); s_genie3_1(); s_d3_vs_d4(); s_limitations()
s_appx_config(); s_appx_table7(); s_appx_glossary()

finish("Dreamer4_Final.pptx", "Dreamer4_Final_speaker_notes.md", "Dreamer 4, final talk (world-models framing): speaker notes")
