"""Build the Dreamer 4 deep-dive deck (50 slides). Run: python3 build_deck.py   (NO_MOVIE=1 OUT=... for the poster-only PDF source)
All numbers come from Hafner, Yan, Lillicrap, "Training Agents Inside of Scalable World Models" (arXiv 2509.24527); figures from the paper/project page."""
from deck_common import *
from deck_slides import *

s_title()
s_agenda()
s_tldr()
s_video()
section("Background & motivation", "World models, learning in imagination, and why Minecraft from offline data is a hard test", 1)
s_why_wm()
s_what_made_hard()
s_testbed()
s_tech_tree()
s_predecessors()
section("Method", "One transformer, three phases: world-model pretraining → agent fine-tuning → imagination training", 2)
s_three_phases()
s_stack_1()
s_stack_2()
s_wm_design()
s_tokenizer()
s_dynamics()
s_primer_flow()
s_primer_df()
s_primer_shortcut()
s_shortcut_forcing()
s_xpred()
s_efficient()
s_agent_tokens()
s_pmpo()
section("Experiments", "Real-time play-testing, the offline diamond challenge, ablations, label efficiency, robotics", 3)
s_table1()
s_wm_compare_1()
s_wm_compare_2()
s_interaction_frames()
s_diamond_results()
s_ablations()
s_label_efficiency()
s_fig1_rollouts()
s_beyond_minecraft()
s_d3_vs_d4()
s_compute()
section("Discussion", "Limitations, critical reading, future work, takeaways", 4)
s_limitations()
s_critical()
s_genie3_1()
s_genie3_2()
s_future()
s_takeaways()
s_questions()
s_references()
state["part"] = "Appendix"
s_appx_config()
s_appx_table2()
s_appx_table7()
s_appx_glossary()

finish("Dreamer4_Deep_Dive.pptx", "Dreamer4_Deep_Dive_speaker_notes.md", "Dreamer 4 — deep dive: speaker notes")
