"""Slide functions for the Dreamer 4 decks. Each function builds one slide (title via new_slide, body, speaker notes) and returns it.
Generated from the linear v6 build script; edit here, then rebuild with build_deck.py / build_final.py."""
from deck_common import *

def s_title():
    """title"""
    # 1 Title -----------------------------------------------------------------
    s = prs.slides.add_slide(BLANK); state["n"] += 1; state["titles"].append("Dreamer 4: Training Agents Inside of Scalable World Models (title)")
    bg = s.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, W, H); bg.fill.solid(); bg.fill.fore_color.rgb = NAVY; bg.line.fill.background()
    # right-hand strips: imagined rollout, human play inside the model, robot world model (all model-generated frames)
    strip_w, strip_h = Inches(5.433), Inches(2.5); sx = W - strip_w
    for i, (f, pre, anchor) in enumerate([("frame_imag_treechop.jpg", (0, 0, 634, 356), "top"),      # game view only (the clip also shows reward/value traces)
                                          ("frame_diamond_dreamer.jpg", None, "top"), ("frame_realworld_soar1.jpg", None, "center")]):
        im = Image.open(A + f).convert("RGB")
        if pre: im = im.crop(pre)
        tw, th = im.width, int(im.width * strip_h / strip_w)
        if th > im.height: th = im.height; tw = int(im.height * strip_w / strip_h)
        l = (im.width - tw) // 2; t = 0 if anchor == "top" else (im.height - th) // 2
        im.crop((l, t, l + tw, t + th)).save(A + f"title_strip_{i}.jpg", quality=88)
        s.shapes.add_picture(A + f"title_strip_{i}.jpg", sx, i * strip_h, width=strip_w, height=strip_h)
    kicker(s, Inches(0.8), Inches(1.55), Inches(6), "Paper deep dive  ·  arXiv 2509.24527", color=SKY, size=11)
    add_text(s, Inches(0.75), Inches(1.95), Inches(6.8), Inches(1.3), "Dreamer 4", size=64, bold=True, color=WHITE)
    add_text(s, Inches(0.8), Inches(3.1), Inches(6.4), Inches(1.4), ["Training Agents Inside of", "Scalable World Models"], size=26, color=WHITE, line_spacing=1.1)
    hline(s, Inches(0.85), Inches(4.55), Inches(0.9), color=SKY, pt=1.5)
    add_text(s, Inches(0.8), Inches(4.75), Inches(6.6), Inches(1.0), ["Danijar Hafner*, Wilson Yan*, Timothy Lillicrap (Google DeepMind)", "29 September 2025  ·  danijar.com/project/dreamer4"], size=15, color=RGBColor(0xC9, 0xD3, 0xE6), line_spacing=1.2)
    add_text(s, Inches(0.8), Inches(6.55), Inches(6.6), Inches(0.4), "Presenter ____________     Date ____________     ~45–60 min incl. discussion", size=11.5, color=RGBColor(0x8F, 0x9B, 0xB8))
    caption(s, Inches(0.8), Inches(6.95), Inches(6.6), "Right, all generated by the Dreamer 4 world model: an imagined rollout, a human playing inside the model, and the robot-arm model.", size=9)
    notes(s, "Welcome. This talk goes through Dreamer 4, the September 2025 DeepMind paper by Danijar Hafner, Wilson Yan and Tim Lillicrap. "
             "Headline: an agent that learns to obtain diamonds in Minecraft purely from offline video, by training inside a learned world model that runs in real time on a single GPU. "
             "The three frames on the right are all generated by the world model: an imagined training rollout, a human play-testing session, and the robot-arm model.")

    # 2 Agenda -----------------------------------------------------------------
    return s

def s_agenda():
    """Agenda"""
    s = new_slide("Agenda")
    numbered(s, Inches(0.6), Inches(1.7), Inches(6.9), [
        ("Background", "why world models, what made scaling them hard, the offline diamond challenge"),
        ("Method", "tokenizer, dynamics transformer, shortcut forcing, agent tokens, imagination training (PMPO)"),
        ("Experiments", "real-time human play-testing, diamond challenge, ablations, learning from unlabeled video, robotics"),
        ("Discussion", "limitations, critical reading, future work, takeaways"),
        ("Appendix", "hyper-parameters, full tables, glossary")], size=16, gap=0.3, num_w=0.6, head_w=2.0)
    note(s, Inches(8.3), Inches(1.75), Inches(4.5), Inches(3.6), "How to read this deck", [
        "Equations are kept to the minimum needed for intuition; the appendix has the exact settings.",
        "Every number is from the paper's tables (Table 1, 2, 7, 8) or the authors' talks; each slide names its source.",
        "Figures © the authors (arXiv 2509.24527 / danijar.com), reproduced for discussion.",
        "Suggested pacing: Parts 1–2 ≈ 25 min, Part 3 ≈ 15 min, Part 4 ≈ 10 min + Q&A."], size=12.5)
    notes(s, "Four parts plus an appendix. For a mixed audience I'll spend most time on the method intuition and on what the experiments do and do not show.")

    # 3 TL;DR -----------------------------------------------------------------
    return s

def s_tldr():
    """Dreamer 4 in one slide"""
    s = new_slide("Dreamer 4 in one slide", "What the paper claims, and the evidence behind each claim")
    rows = [["Claim", "Evidence in the paper"],
            ["First agent to obtain diamonds in Minecraft from offline data only", "0.7 % of 1,000 × 60-min episodes reach a diamond; 29 % reach an iron pickaxe (vs 11 % for a Gemma-3 VLA, 0.6 % for BC); Table 7"],
            ["A world model that simulates Minecraft object interactions and menus accurately, in real time on 1 GPU", "Human play-testers solve 14/16 interaction tasks inside it at 21 FPS with a 9.6 s context (Oasis: 5/16, Lucid-v1: 0/16); Table 1"],
            ["Shortcut forcing + an efficient transformer make this fast", "4 sampling steps instead of 16–64; FVD 306 → 57 across the design cascade while going from 0.8 to 21 FPS; Table 2 and Fig. 8"],
            ["Action conditioning can be learned from few labels", "100 h of labeled actions ≈ 85 % PSNR / 100 % SSIM of using all 2,541 h; actions transfer to Nether/End seen only unlabeled; Fig. 7"],
            ["~100× less data than VPT, no environment interaction", "2,541 h contractor video vs VPT's 270 K h web video + online RL; Table 3"]]
    add_table(s, Inches(0.5), Inches(1.55), Inches(12.3), rows, col_widths=[4.6, 7.7], font=12.5, row_h=0.8)
    notes(s, "Five claims, each tied to a table or figure. The numbers are candid: diamonds are rare (0.7 %), but every earlier milestone is reached far more reliably and faster than by the baselines, without a single environment step.")


    # 4 The official video ---------------------------------------------------------------
    return s

def s_video():
    """The paper in three minutes: the official video"""
    s = new_slide("The paper in three minutes: the official video",
                  "'Dreamer 4 | Diamonds from Offline Experience', Danijar Hafner's channel, 1 Oct 2025, 2:55. Figure 1 in motion")
    V = A + "video/"
    pic = s.shapes.add_picture(V + "yt_thumb_16x9.jpg", Inches(0.5), Inches(1.5), width=Inches(7.9), height=Inches(4.444)); click_through(pic, YT)
    pic.line.color.rgb = RULE; pic.line.width = Pt(0.75)
    cx, cy = Inches(0.5 + 7.9 / 2), Inches(1.5 + 4.444 / 2)
    ring = s.shapes.add_shape(MSO_SHAPE.OVAL, cx - Inches(0.55), cy - Inches(0.55), Inches(1.1), Inches(1.1)); ring.fill.solid(); ring.fill.fore_color.rgb = WHITE; ring.line.fill.background(); click_through(ring, YT)
    tri = s.shapes.add_shape(MSO_SHAPE.ISOSCELES_TRIANGLE, cx - Inches(0.19), cy - Inches(0.25), Inches(0.44), Inches(0.5)); tri.rotation = 90; tri.fill.solid(); tri.fill.fore_color.rgb = NAVY; tri.line.fill.background(); click_through(tri, YT)
    caption_links(s, Inches(0.5), Inches(6.0), Inches(7.9), [("\u25b6 Click the picture to open the video on YouTube (internet required): ", None), ("youtube.com/watch?v=oDlBtTcX0g0", YT)], size=11)
    caption_links(s, Inches(0.5), Inches(6.35), Inches(7.9), [("Project page: 60 more clips (imagination rollouts, 17 interaction tasks \u00d7 3 models, robot arm): ", None), ("danijar.com/project/dreamer4", PROJECT)], size=10)
    # right column: QR + facts, what to watch for, embedded offline fallback
    s.shapes.add_picture(V + "qr_video.png", Inches(8.7), Inches(1.5), width=Inches(1.35), height=Inches(1.35))
    add_text(s, Inches(10.15), Inches(1.5), Inches(2.7), Inches(1.4), ["**Scan to watch on your own device**", "2:55 \u00b7 uploaded 1 Oct 2025", "YouTube channel @danijar (Danijar Hafner)", "Description: 'the first agent to mine diamonds learning entirely offline'"], size=10.5, color=GREY, bold_color=NAVY, line_spacing=1.15)
    note(s, Inches(8.7), Inches(3.0), Inches(4.13), Inches(1.5), "What to watch for", [
        "The imagined training rollouts of Figure 1 in motion (chopping, crafting menus, mining, cave lighting, diamond ore), decoded from latents for viewing",
        "The headline it builds up to: diamonds from 2,541 h of offline video, no environment interaction"], size=11)
    kicker(s, Inches(8.7), Inches(4.6), Inches(4.2), "No internet? Embedded 10-s teaser, click to play", color=MUTED, size=8)
    if os.environ.get("NO_MOVIE"):   # PDF render: poster frame only (LibreOffice would otherwise embed the clip as a Screen annotation)
        s.shapes.add_picture(V + "teaser_poster.jpg", Inches(8.7), Inches(4.85), Inches(3.64), Inches(2.05))
    else:
        mov = s.shapes.add_movie(MEDIA + "official_danijar_com/teaser.mp4", Inches(8.7), Inches(4.85), Inches(3.64), Inches(2.05), poster_frame_image=V + "teaser_poster.jpg", mime_type="video/mp4")
    notes(s, "Play the official video here (2:55), or the embedded ten-second teaser on the right if the room has no internet. The video is Figure 1 in motion: imagined rollouts decoded for visualisation, "
             "building up to the headline claim. Say it explicitly: what you see there is generated by the world model, not recorded gameplay. "
             "The four uncut 60-minute evaluation episodes on the same channel show the trained agent in the real game (linked on the results slide). "
             "YouTube does not allow downloading, so the deck only links to the video; the teaser and the 60 project-page clips are archived in dreamer4_resources/media/. "
             "If you prefer to show the video later, the natural spot is the Figure 1 slide in Part 3.")

    # ---- Part 1 -------------------------------------------------------------
    return s

def s_why_wm():
    """Why world models? Learning in imagination"""
    # 5 Why world models ---------------------------------------------------------
    s = new_slide("Why world models? Learning in imagination", "The Dreamer lineage: same idea, increasingly capable simulators")
    add_bullets(s, Inches(0.6), Inches(1.55), Inches(6.4), Inches(4.2), [
        "A world model is a learned simulator: given the current situation and an action, it predicts what happens next",
        "Imagination training optimises the policy on rollouts generated *by the model* instead of by the real environment, which makes experience cheap, parallel and safe",
        "Why it matters now: robots and other real-world systems cannot afford millions of trial-and-error interactions, while video of the world is abundant",
        "Dreamer 4's bet: if the simulator gets object interactions right, RL inside it can go beyond what pure imitation learns"], size=17)
    # timeline
    y = Inches(6.0); xs = [0.7, 3.7, 6.7, 9.7]; items = [("Dreamer (2019)", "latent imagination on DM Control"), ("DreamerV2 (2020)", "discrete latents, Atari"), ("DreamerV3 (2023/Nature 2025)", "one config for 150+ tasks; diamonds with online RL"), ("Dreamer 4 (2025)", "transformer diffusion WM; diamonds offline; real-time on 1 GPU")]
    hline(s, Inches(0.9), y + Inches(0.2), Inches(11.4), color=RULE, pt=1)
    for (x, (t, d)) in zip(xs, items):
        dot = s.shapes.add_shape(MSO_SHAPE.OVAL, Inches(x + 0.14), y + Inches(0.12), Inches(0.17), Inches(0.17)); dot.fill.solid(); dot.fill.fore_color.rgb = BLUE if "4" in t else NAVY; dot.line.fill.background()
        add_text(s, Inches(x), y + Inches(0.4), Inches(2.9), Inches(0.8), [f"**{t}**", d], size=11, color=GREY, bold_color=NAVY)
    fit_picture(s, A + "frame_imag_treechop.jpg", Inches(7.3), Inches(1.6), Inches(5.5), Inches(3.4))
    caption(s, Inches(7.3), Inches(5.05), Inches(5.5), "Imagined rollout decoded for visualisation, with the agent's reward and value estimates (project page, 'Gather wood').")
    notes(s, "The core idea has been constant since the first Dreamer in 2019: learn a model of the environment, then train the policy on imagined trajectories. "
             "What changed in Dreamer 4 is the simulator: a 2-billion-parameter block-causal transformer trained with a diffusion-style objective, accurate enough that a human can play inside it. "
             "The frame on the right is an imagined rollout, not the real game.")

    # 6 What made it hard ------------------------------------------------------------
    return s

def s_what_made_hard():
    """What made scalable world models hard before"""
    s = new_slide("What made scalable world models hard before", "Three requirements pulled in different directions")
    columns(s, Inches(1.55), Inches(2.85), [("Fidelity of interactions", ["Video generators look good but get game mechanics wrong: inventories, crafting menus, breaking blocks, placing a boat and riding it.", "Prior Minecraft world models (Oasis, Lucid-v1, MineWorld) fail most such tasks."]), ("Speed", ["Imagination RL needs millions of generated frames, and a human tester needs at least 20 FPS.", "Diffusion transformers spend tens of denoising steps per frame: 0.8 FPS for the baseline in this paper."]), ("Memory & drift", ["Autoregressive video drifts: small errors feed back into the context.", "Short contexts (1–2 s in prior models) forget what is behind the player."])], size=13, head_size=15)
    add_bullets(s, Inches(0.6), Inches(4.5), Inches(12.2), Inches(2.3), [
        "Dreamer 3's RSSM is fast (about 1,000× faster than a diffusion transformer) but works at 64×64 pixels and needed abstract inventory state and crafting actions instead of raw mouse and keyboard input",
        "Dreamer 4's answer: a diffusion transformer that needs only 4 sampling steps (shortcut forcing), an architecture tuned for long context at low cost, and training choices that keep long rollouts stable (x-prediction, noised context)"], size=16)
    notes(s, "Three tensions: fidelity versus speed versus stability over long horizons. Prior Minecraft world models chose speed and looked plausible, but a human trying to craft a pickaxe inside them fails. "
             "The recurrent Dreamer 3 model was fast but low-resolution and relied on privileged state. Dreamer 4 tries to get all three at once.")

    # 7 The offline diamond challenge -------------------------------------------------
    return s

def s_testbed():
    """The test bed: the offline diamond challenge"""
    s = new_slide("The test bed: the offline diamond challenge", "No environment interaction at all: everything is learned from 2,541 hours of human gameplay video")
    add_bullets(s, Inches(0.6), Inches(1.55), Inches(6.6), Inches(5.2), [
        "**Data:** OpenAI VPT contractor recordings (subsets 6–10), 2,541 h at 360×640, 20 FPS, with mouse & keyboard labels; 90/10 train/eval split by 5-minute chunk",
        "**Actions:** 23 binary keys + 121-way mouse class (11×11 foveated bins, VPT convention); no abstract 'craft' actions",
        "**Evaluation:** 1,000 fresh random worlds, empty inventory, 60 min each (72,000 actions at 20 FPS); a fixed prompt sequence walks the agent through the 12-item tech tree",
        "Why it is hard: diamonds sit ~24,000 actions deep for a human; rewards are sparse; offline data covers the late tech tree thinly; every skill (chop → craft → mine → smelt) must chain without a single trial in the real game",
        "**Baselines, all on the same data:** VPT fine-tuned, BC, BC without task input, a VLA built on Gemma 3, and 'WM + BC' (Dreamer 4 without imagination RL)"], size=15.5)
    fit_picture(s, A + "frame_diamond_dreamer.jpg", Inches(7.5), Inches(1.6), Inches(5.3), Inches(3.0))
    caption(s, Inches(7.5), Inches(4.62), Inches(5.3), "Diamond ore, as simulated by the world model during a human 'mine diamonds' session (project page).")
    tree = "log → planks → crafting table → stick → wooden pickaxe → cobblestone → stone pickaxe → iron ore → furnace → iron ingot → iron pickaxe → diamond"
    box(s, Inches(7.5), Inches(5.1), Inches(5.3), Inches(1.6), "The 12 milestones (Table 5)", [tree], fill=PALE_BLUE, size=12)
    notes(s, "Offline means offline: the agent never touches Minecraft during training. The only signal is human gameplay video with logged inputs. "
             "Diamonds need a long chain of subgoals, each executed with raw mouse and keyboard at 20 Hz. That is why success rates fall off steeply along the tech tree for every method.")

    # 8 Tech tree ---------------------------------------------------------------
    return s

def s_tech_tree():
    """The tech tree: twelve milestones, three tool gates"""
    s = new_slide("The tech tree: twelve milestones, three tool gates", "Why diamonds are a long-horizon problem, and where each agent falls off (Tables 7 and 8)")
    fit_picture(s, jpeg(A + "diag_tech_tree.png", max_w=2400, q=90), Inches(0.4), Inches(1.45), Inches(12.5), Inches(5.4))
    notes(s, "The whole challenge on one picture. Top row: the twelve milestone items in the order the evaluation prompts them, grouped into wood, stone and iron ages and the diamond. The amber gates are game rules, not choices: stone only drops if you hold a wooden pickaxe, iron ore needs a stone pickaxe, diamonds need an iron pickaxe; mining with a weaker tool destroys the block. "
             "So there is no shortcut; every item depends on the previous tool, and each step is a different skill: punching, menu navigation with the mouse, placing blocks, digging, smelting. The minutes under the boxes are Dreamer 4's mean time to each item over successful episodes, Table 8: about 13 minutes to the iron pickaxe, 21 to a diamond; humans take about 20. "
             "Bottom: success rates from Table 7. Every agent nails the wood age; VPT's offline policy already dies at the wooden pickaxe; the Gemma-3 VLA and Dreamer 4 separate from the stone pickaxe on, and the gap grows with the horizon: 29 versus 11 percent at the iron pickaxe, and only Dreamer 4 ever reaches a diamond. Keep this curve in mind; Part 3 asks where the gap comes from.")

    # 9 Predecessors ---------------------------------------------------------------
    return s

def s_predecessors():
    """Who reached diamonds before, and what it cost"""
    s = new_slide("Who reached diamonds before, and what it cost", "Table 3: same goal, very different regimes. The hours of data and interaction behind each agent")
    fit_picture(s, jpeg(A + "chart_agent_cost.png", max_w=1800, q=90), Inches(0.4), Inches(1.5), Inches(7.9), Inches(5.35))
    box(s, Inches(8.7), Inches(1.6), Inches(4.2), Inches(1.75), "VPT (OpenAI, 2022)", ["Showed that web video plus an inverse-dynamics model can bootstrap a mouse-and-keyboard policy. Diamonds still took 194K hours of trial and error in the live game, and the pure behavioural-cloning variant never crafts a wooden pickaxe offline."], size=12)
    box(s, Inches(8.7), Inches(3.45), Inches(4.2), Inches(1.55), "Dreamer 3 (2023)", ["Reached diamonds from scratch by online RL inside a small recurrent world model, at 64×64 pixels, with inventory state as input and abstract crafting actions instead of mouse clicks in menus."], size=12)
    box(s, Inches(8.7), Inches(5.1), Inches(4.2), Inches(1.75), "Dreamer 4's bet", ["Keep the human interface (360×640 pixels, raw mouse & keyboard), drop environment interaction entirely, and get the missing experience from imagination instead of the game, with 100× less data than the keyboard-and-mouse agents before it (Table 3 caption)."], size=12, accent=NAVY)
    notes(s, "Historical context, with the hours on a log scale because they span three orders of magnitude. VPT is the closest relative: same contractor data, same action space. It got to diamonds, but only after pseudo-labelling 270 thousand hours of YouTube and then playing the real game for 194 thousand hours of RL; its offline-only version is the grey line that collapsed on the previous slide. "
             "Dreamer 3 got there with far less experience, but it changed the problem: tiny images, privileged inventory state, and crafting as an abstract action instead of a sequence of mouse movements in a menu. Dreamer 4 keeps the hard interface and removes the interaction. That is the claim in the paper's title, and the number to remember is zero hours in the game.")

    # ---- Part 2 -------------------------------------------------------------
    return s

def s_three_phases():
    """Overview: three phases, one transformer"""
    # 9 Three phases ---------------------------------------------------------------
    s = new_slide("Overview: three phases, one transformer", "Algorithm 1 in the paper")
    cols = [("Phase 1 · World-model pretraining", ["Train the causal tokenizer (masked autoencoding), then freeze it", "Train the interactive dynamics model on tokenized video ± actions with shortcut forcing", "Inputs: all 2,541 h, labeled or not"], BLUE),
            ("Phase 2 · Agent fine-tuning", ["Insert agent tokens with task embedding; add policy & reward heads", "Behavioural cloning with multi-token prediction (L = 8) on task-relevant data", "Dynamics loss continues on uniform data so the model stays honest"], TEAL),
            ("Phase 3 · Imagination training", ["Freeze the transformer; train policy + value heads only", "Roll out the policy inside the world model, reward from the learned reward head", "PMPO with reverse-KL to the frozen BC policy; γ = 0.997"], PURPLE)]
    columns(s, Inches(1.55), Inches(3.7), [(t.split(" · ")[1][0].upper() + t.split(" · ")[1][1:], body) for (t, body, col) in cols], gap=Inches(0.55), num_label=lambda k: f"Phase {k}", arrows=True, bullets=True, size=13, head_size=15)
    add_bullets(s, Inches(0.6), Inches(5.4), Inches(12.2), Inches(1.6), [
        "One block-causal transformer design is used for the tokenizer, the dynamics model and the agent backbone; policy and value are small heads on 'agent tokens'",
        "Data mix in phases 2 and 3: 50 % uniform sequences, 50 % task-relevant; the BC loss is applied only to relevant data and the dynamics loss only to uniform data ('to avoid optimistic generations')"], size=14.5)
    notes(s, "Three phases. First a world model is trained on all video. Second, agent tokens and heads are added and trained by behavioural cloning while the dynamics loss keeps running. Third, the transformer is frozen and only the policy and value heads are trained by RL on imagined rollouts. "
             "Applying the dynamics loss to uniform data only is a small but deliberate choice: it avoids a world model that is optimistic about task success.")

    # 9b/9c How the pieces fit together (system diagram, two halves) ---------------------------
    return s

def _eq(slide, name, left, top, max_w, scale=0.74):
    """Place a rendered equation (assets/eq_*.png, 300 dpi) at a consistent scale; returns the y below it."""
    im = Image.open(A + f"{name}.png"); w = Inches(im.width / 300 * scale); h = Inches(im.height / 300 * scale)
    if w > max_w: h = int(h * max_w / w); w = max_w
    slide.shapes.add_picture(A + f"{name}.png", left, top, width=w, height=h)
    return top + h

def s_algorithm1_a():
    """Algorithm 1 in full (1/2): Phase 1, world-model pretraining"""
    s = new_slide("Algorithm 1 in full (1/2): Phase 1, world-model pretraining", "Each step of the recipe with its objective written out; equation numbers are the paper's (§3.1 and §3.2)")
    # left: tokenizer
    x, w = Inches(0.6), Inches(5.5)
    kicker(s, x, Inches(1.5), w, "Step 1 · Train the tokenizer on videos, eq. (5)", color=BLUE, size=10.5); hline(s, x, Inches(1.8), w, color=RULE)
    y = _eq(s, "eq5", x, Inches(1.95), w)
    add_bullets(s, x, y + Inches(0.15), w, Inches(4.5), [
        "Masked autoencoding: in every frame a random fraction p ~ U(0, 0.9) of the 16×16 input patches is replaced by a learned mask embedding; the decoder must reconstruct the full frame from the 256 latent tokens (512×16 tanh bottleneck)",
        "MSE keeps colours and layout; LPIPS keeps textures. Like every loss term in the paper, both are divided by a running estimate of their root-mean-square, which is why a fixed weight of 0.2 works",
        "Encoder and decoder are causal in time, so the same tokenizer runs frame by frame at inference, with p = 0",
        "≈ 400 M parameters; trained once on all 2,541 h of video, then frozen for everything that follows"], size=13, space=6)
    # right: dynamics
    x, w = Inches(6.5), Inches(6.3)
    kicker(s, x, Inches(1.5), w, "Step 2 · Train the world model on tokenized video ± actions, eqs. (6)–(8)", color=BLUE, size=10.5); hline(s, x, Inches(1.8), w, color=RULE)
    y = _eq(s, "eq6", x, Inches(1.95), w)
    add_text(s, x, y + Inches(0.08), w, Inches(0.5), "Every frame is corrupted to its own signal level τ_t; the network sees the noisy latents, τ, the step size d and the actions, and predicts the clean latents (x-prediction). Loss (7): a flow-matching term at the smallest step size, a bootstrap term for larger steps:", size=11, color=GREY)
    y = _eq(s, "eq7a", x, y + Inches(0.78), w)
    y = _eq(s, "eq7b", x, y + Inches(0.08), w)
    y = _eq(s, "eq7c", x, y + Inches(0.1), w)
    add_text(s, x, y + Inches(0.1), Inches(3.4), Inches(0.3), "Every term is multiplied by the ramp weight (8):", size=11, color=GREY)
    y = _eq(s, "eq8", x + Inches(3.45), y + Inches(0.08), Inches(2.0))
    add_bullets(s, x, y + Inches(0.12), w, Inches(1.6), [
        "The bootstrap target b′, b″ is two half-steps computed by the model itself (stop-gradient); it is formed in v-space and scaled back to x-space by (1 − τ)²",
        "Unlabeled frames use a learned 'no action' embedding, so labeled and unlabeled video train the same loss; at inference K = 4 steps of d = 1/4 per frame, past frames kept at τ_ctx = 0.1"], size=12, space=5)
    notes(s, "This is Algorithm 1 written out, first phase. Step one trains the tokenizer on video alone with equation five: reconstruct each frame from its 256 latent tokens, mean squared error plus 0.2 times LPIPS, with random patch masking so the latents have to carry context. "
             "Step two trains the dynamics model on the tokenized video with equations six to eight. Six is the setup: every frame gets its own signal level, the clean latents are mixed with Gaussian noise, and the network predicts the clean latents from the noisy ones, the signal level, the step size and the actions. "
             "Seven is the loss with two cases: for the smallest step size it is a plain squared error against the clean latents, the flow-matching term; for larger step sizes the target is what two half-steps of the model itself would produce, with the gradient stopped, which is the shortcut bootstrap. The (1 minus tau) squared factor converts that v-space comparison back into x-space units. "
             "Eight is the ramp weight that multiplies everything: noisier frames carry less learning signal, so they get less weight. Actions are optional: unlabeled frames use a learned 'no action' embedding.")
    return s

def s_algorithm1_b():
    """Algorithm 1 in full (2/2): Phases 2 and 3, agent fine-tuning and imagination training"""
    s = new_slide("Algorithm 1 in full (2/2): Phases 2 and 3", "Agent fine-tuning with eqs. (7) + (9), then imagination training with eqs. (10) and (11); the Phase 1 transformer stays the backbone (§3.3)")
    # left: phase 2
    x, w = Inches(0.6), Inches(5.7)
    kicker(s, x, Inches(1.5), w, "Phase 2 · Agent fine-tuning, eqs. (7) + (9)", color=BLUE, size=10.5); hline(s, x, Inches(1.8), w, color=RULE)
    add_bullets(s, x, Inches(1.95), w, Inches(1.5), [
        "Insert agent tokens as an extra modality in every frame. They receive the task embedding q_t and attend to latents, actions and the past; nothing attends back to them, so the world model cannot be steered by the task",
        "Policy and reward heads are small MLPs on the agent-token outputs h_t, with one output layer per prediction distance n = 0 … L (multi-token prediction):"], size=12.5, space=5)
    y = _eq(s, "eq9", x, Inches(3.5), w)
    add_bullets(s, x, y + Inches(0.15), w, Inches(2.6), [
        "Reward head: symexp twohot distribution over the game-event rewards. Policy head: categorical for the mouse class, vectorised binary for the 23 keys",
        "The pretraining loss (7) keeps running on the same noised latents, so the world model does not degrade. Data mix: 50 % uniform sequences (dynamics loss) and 50 % task-relevant sequences (BC and reward loss)",
        "Output of this phase: the 'WM + BC' agent (iron pickaxe 16.9 %, no diamonds)"], size=12.5, space=5)
    # right: phase 3
    x, w = Inches(6.7), Inches(6.1)
    kicker(s, x, Inches(1.5), w, "Phase 3 · Imagination training, eqs. (10) + (11)", color=BLUE, size=10.5); hline(s, x, Inches(1.8), w, color=RULE)
    add_bullets(s, x, Inches(1.95), w, Inches(1.5), [
        "Freeze the transformer. Add a value head and keep a frozen copy of the policy head as behavioural prior π_prior",
        "Rollouts start from dataset contexts, one per context: the flow head samples the next latents (K = 4 steps), the policy head samples the action; the reward head labels each step r_t, the value head v_t",
        "Value head: TD learning on λ-returns, γ = 0.997, c_t = 1 for non-terminal states, symexp twohot output"], size=12, space=4)
    y = _eq(s, "eq10", x, Inches(3.75), w)
    add_text(s, x, y + Inches(0.1), w, Inches(0.3), "Policy head, PMPO; only the sign of the advantage enters:", size=12, color=DARK)
    y = _eq(s, "eq11", x, y + Inches(0.42), w)
    y = _eq(s, "eq11b", x, y + Inches(0.1), w)
    add_bullets(s, x, y + Inches(0.1), w, Inches(0.9), [
        "α = 0.5 balances the positive and negative sets; the KL runs in the reverse direction of the original PMPO to keep the policy inside the prior's support; all three terms are in nats. Only the policy and value heads receive gradients"], size=12, space=4)
    notes(s, "Second and third phase. Phase two turns the world model into an agent. Agent tokens are inserted into the sequence and carry the task; they can read everything, nothing can read them. On their outputs sit two small heads trained with equation nine: the policy head predicts the next L plus one actions and the reward head the next L plus one rewards, both as log-likelihoods, with L equal to eight. "
             "Equation seven stays switched on during this phase, on the uniform half of the data, so the world model keeps its accuracy. "
             "Phase three is imagination training. The transformer is frozen. Rollouts start from real contexts; the model generates the latents, the policy head picks the actions, and the reward and value heads label the trajectory. The value head is trained by equation ten, a TD loss towards lambda-returns with discount 0.997. "
             "The policy head is trained by equation eleven, PMPO: states with positive advantage get their action's log-probability pushed up, states with negative advantage pushed down, each set averaged separately with weight alpha equal to one half, and a KL term with weight 0.3 keeps the policy close to the frozen behavioural-cloning prior. Because only the sign of the advantage enters, there is nothing to normalise, and the three terms can be added directly because all of them are measured in nats.")
    return s

def s_stack_1():
    """How the pieces fit together (1/2): data → tokenizer → one transformer"""
    s = new_slide("How the pieces fit together (1/2): data → tokenizer → one transformer", "What flows between the components, and which phase trains which output")
    fit_picture(s, jpeg(A + "diag_stack_model.png", max_w=2400, q=90), Inches(0.4), Inches(1.5), Inches(12.5), Inches(3.75))
    add_bullets(s, Inches(0.6), Inches(5.35), Inches(12.2), Inches(1.6), [
        "Two block-causal transformers: the tokenizer (400 M) turns each frame into 256 latent tokens; the dynamics/agent transformer (1.6 B) predicts the clean next latents and reads policy, reward and value off its agent tokens (MLP heads, multi-token prediction L = 8)",
        "The decoder sits outside the agent's loop: pretraining, fine-tuning and imagination all happen in latent space, and pixels are only rendered for humans",
        "Agent tokens have one-way attention: they see everything and nothing sees them, so adding the agent cannot change what the simulator predicts"], size=13.5)
    notes(s, "This is the system view before we go component by component. Read it left to right: video frames enter the tokenizer encoder and become 256 latent tokens per frame; those latents, noised to a per-frame signal level, go into the big transformer together with the actions, the register tokens and, from phase 2 on, the agent tokens that carry the task id. "
             "The transformer has one output for the world model, the clean latents of the frame, and three outputs for the agent: policy, reward, value. The italic tags say which phase trains which output. "
             "The decoder is only used to make videos and figures; the agent never sees pixels after the encoder. And the agent tokens can read everything but nothing reads them, which keeps the agent from biasing its own simulator.")
    return s

def s_stack_2():
    """How the pieces fit together (2/2): the two loops"""
    s = new_slide("How the pieces fit together (2/2): the two loops", "Training inside the model, and acting in the real game")
    fit_picture(s, jpeg(A + "diag_stack_loops.png", max_w=2400, q=90), Inches(0.4), Inches(1.5), Inches(12.5), Inches(3.3))
    add_bullets(s, Inches(0.6), Inches(4.95), Inches(12.2), Inches(2.0), [
        "Imagination loop (phase 3): start from real latents → policy head samples an action → dynamics predicts the next latents in K = 4 shortcut steps → reward and value heads score the step → PMPO with reverse KL updates the policy and value heads only; one rollout per context, transformer frozen",
        "Acting (evaluation): encoder → transformer → policy head, once per frame at 20 FPS; at test time the world model only provides the representation and generates nothing",
        "What the loop buys: on the same representations, behavioural cloning reaches the iron pickaxe in 16.9 % of episodes and never a diamond; after imagination training, 29 % and 0.7 % (Table 7)"], size=13.5)
    notes(s, "Bottom half of the system view. On the right, the imagination loop: rollouts start from real contexts, the policy proposes actions, the frozen dynamics model predicts what happens in latent space with four forward passes per frame, the learned reward and value heads score the outcome and PMPO nudges the policy toward positive-advantage actions and away from negative ones, with a reverse KL to the frozen behavioural-cloning copy as prior. "
             "Gradients only reach the policy and value heads. On the left, evaluation: in the real game the same transformer runs once per frame as a feature extractor for the policy head; nothing is imagined at test time. The numbers in the last bullet are the reason to do RL inside the model at all.")

    # 10 World model design ----------------------------------------------------------
    return s

def s_wm_design():
    """World-model design"""
    s = new_slide("World-model design", "Figure 2: causal tokenizer + interactive dynamics model, one shared block-causal transformer")
    fit_picture(s, A + "fig2_world_model_design.png", Inches(0.5), Inches(1.55), Inches(7.6), Inches(3.4))
    caption(s, Inches(0.5), Inches(5.0), Inches(7.6), "Left: causal tokenizer (masked patches → latent tokens → reconstruction). Right: interactive dynamics with interleaved action tokens a, latent tokens z, and per-frame signal level τ / step size d; space layers with a causal time layer every 4th block. (Figure 2, arXiv 2509.24527)")
    add_bullets(s, Inches(8.4), Inches(1.6), Inches(4.5), Inches(5.2), [
        "**Parameters:** 2 B in total, ≈ 400 M tokenizer + 1.6 B dynamics",
        "**Frames:** 360×640, zero-padded to 384×640, i.e. 960 patches of 16×16",
        "**Latents:** N_z = 256 tokens × 32 dims per frame (512×16 bottleneck, tanh)",
        "**Context:** 192 frames = 9.6 s at 20 FPS",
        "**Attention:** block-causal, full within a frame and causal across frames, so the model runs online frame by frame",
        "**Block recipe:** pre-RMSNorm, RoPE, SwiGLU, QK-norm, logit soft-capping, register tokens"], size=14.5)
    notes(s, "Both halves use the same transformer block. Block-causal means every token in frame t can see all tokens of frames up to t, which is exactly what you need for online, frame-by-frame generation with a human or a policy in the loop.")

    # 11 Tokenizer ---------------------------------------------------------------
    return s

def s_tokenizer():
    """The causal tokenizer"""
    s = new_slide("The causal tokenizer", "Compress each frame into 256 continuous latent tokens without looking into the future (paper §3.1)")
    fit_picture(s, jpeg(A + "diag_tokenizer.png", max_w=1800, q=88), Inches(0.4), Inches(1.5), Inches(8.1), Inches(4.1))
    caption(s, Inches(0.5), Inches(5.6), Inches(8.0), "Schematic built from one archived world-model frame; the latent grid is illustrative (real latents are 256 tokens × 32 dims, not a 16×16 image).")
    add_bullets(s, Inches(8.75), Inches(1.55), Inches(4.2), Inches(5.3), [
        "**Training:** masked autoencoding (no VAE or VQ): input patches are dropped with probability p ~ U(0, 0.9) and replaced by a learned embedding, so the encoder must infer them from context, which regularises the latent space; p = 0 at inference",
        "**Bottleneck:** latent tokens are read out through a linear projection to 512×16 with a tanh, reshaped to 256 tokens × 32 dims per frame; continuous, no codebook",
        "**Loss:** MSE + 0.2·LPIPS on the reconstructed patches; the perceptual term keeps textures crisp",
        "**Causality:** frame t is encoded and decoded from frames ≤ t only, so the same tokenizer runs frame by frame during live play",
        "Trained once, then frozen (≈ 400 M parameters); Hafner expects end-to-end training to be possible eventually"], size=13, space=5)
    notes(s, "The tokenizer is a masked autoencoder over 16×16 patches with a small continuous bottleneck. Two properties matter downstream: it is causal in time, and its latent space is smooth because of the heavy random masking during training. "
             "Everything after this operates on 256 latent tokens per frame instead of 960 patches. The schematic on the left is an illustration built from a real frame, not a visualisation of the trained model.")

    # 12 Dynamics model ---------------------------------------------------------------
    return s

def s_dynamics():
    """The interactive dynamics model"""
    s = new_slide("The interactive dynamics model", "Predict the clean latents of the next frame from the past, the actions and a noisy guess (paper §3.2)")
    fit_picture(s, jpeg(A + "diag_dynamics.png", max_w=1800, q=88), Inches(0.4), Inches(1.5), Inches(8.1), Inches(4.1))
    caption(s, Inches(0.5), Inches(5.6), Inches(8.0), "Sequence layout and attention pattern (schematic). Three of the 192 context frames are shown.")
    add_bullets(s, Inches(8.75), Inches(1.55), Inches(4.2), Inches(5.3), [
        "**Sequence per frame:** action tokens (23 keys + mouse class, or a learned 'no action' embedding for unlabeled video), one token for signal level τ_t and step size d, the 256 latent tokens, register tokens",
        "**Attention:** everything within a frame sees each other; across frames only the past. Space-only layers do most of the work; a causal time layer every 4th layer sees the 192-frame (9.6 s) context",
        "**Training target:** the clean latents of every frame (x-prediction) from their noised versions, the past and the actions; one loss over the whole sequence",
        "**Efficiency:** grouped-query attention, alternating 64/256-frame batches and register tokens; 1.6 B parameters run at 21 FPS on one H100 with K = 4",
        "**Inference:** past frames are kept slightly corrupted (the paper's τ_ctx) so small generation errors do not push the model off-distribution"], size=13, space=5)
    notes(s, "The dynamics model reads the interleaved sequence of actions and latents. Only every fourth layer attends across time; the rest work within one frame. That is what makes a 9.6 s context affordable. "
             "Alternating short and long batches is a training-cost trick: it cut a training step from 9.8 s to 1.5 s in the ablation (Table 2). "
             "A wording note: the paper says the past inputs are 'slightly corrupted to signal level τ_ctx = 0.1'. Read that as a small amount of noise on the context, not as 90 % noise.")

    # 13 Primer 1: flow matching ---------------------------------------------------------------
    return s

def s_primer_flow():
    """Primer 1 of 3 · Flow matching: one dial from noise to image"""
    s = new_slide("Primer 1 of 3 · Flow matching: one dial from noise to image", "The background the dynamics objective is built on (paper §2)")
    fit_picture(s, jpeg(A + "diag_flow.png", max_w=1800, q=88), Inches(0.5), Inches(1.5), Inches(12.3), Inches(3.3))
    add_bullets(s, Inches(0.6), Inches(4.95), Inches(12.2), Inches(2.0), [
        "**Signal level τ ∈ [0, 1]:** x(τ) = (1 − τ)·ε + τ·x, where τ = 0 is pure noise and τ = 1 the clean latent; during training τ is drawn at random for every example",
        "The network learns a direction: f(x(τ), τ) ≈ v = x − ε, the velocity pointing from noise to data; sampling starts from noise and walks to τ = 1 in K steps",
        "Two equivalent parameterisations: predict the velocity v (standard) or the clean latent x directly (x-prediction); the maths is identical, but the error behaviour under autoregressive feedback differs (see the x-prediction slide)",
        "Why so many steps? The learned direction is only locally right, so ordinary diffusion needs 16–64 small steps per image, far too slow for a 20 FPS simulator"], size=13.5, space=5)
    notes(s, "For the non-diffusion people: think of a dial τ from 0 (pure noise) to 1 (clean latent). Training corrupts a clean latent to a random position on the dial and asks the network for the way back, either as a direction (velocity) or as the clean end point. "
             "Sampling turns the dial from 0 to 1 in K steps. The strip at the top is a real world-model frame mixed with Gaussian noise at five signal levels. The problem for a real-time simulator is K: standard models need dozens of steps per frame.")

    # 14 Primer 2: diffusion forcing ---------------------------------------------------------------
    return s

def s_primer_df():
    """Primer 2 of 3 · Diffusion forcing: a noise level per frame"""
    s = new_slide("Primer 2 of 3 · Diffusion forcing: a noise level per frame", "Chen et al., 2024: what makes causal, frame-by-frame generation possible")
    fit_picture(s, jpeg(A + "diag_forcing.png", max_w=1800, q=88), Inches(0.5), Inches(1.5), Inches(12.3), Inches(3.5))
    add_bullets(s, Inches(0.6), Inches(5.1), Inches(12.2), Inches(1.9), [
        "Standard video diffusion corrupts the whole clip with one τ: past and future are always equally noisy, so the model cannot be rolled out one frame at a time",
        "Diffusion forcing draws an independent τ_t for every frame; each frame is at once a denoising target and (noisy) history for the frames after it, with a single loss over the whole sequence",
        "What it buys at inference: the next frame is generated from pure noise given a clean or lightly noised past, which is exactly the interactive setting; keeping the past slightly noised makes the model tolerant of its own small mistakes",
        "What it does not fix: still tens of denoising steps for every frame, the 0.8 FPS starting point of the design cascade (Table 2)"], size=13.5, space=5)
    notes(s, "Diffusion forcing is the trick that turns a video diffusion model into a causal simulator: every frame gets its own noise level, so the model learns to predict a noisy future from a cleaner past. "
             "That is precisely the situation at inference, where the past is what the model generated a moment ago. What it does not solve is speed; that is what shortcut models are for.")

    # 15 Primer 3: shortcut models ---------------------------------------------------------------
    return s

def s_primer_shortcut():
    """Primer 3 of 3 · Shortcut models: learning to take big steps"""
    s = new_slide("Primer 3 of 3 · Shortcut models: learning to take big steps", "Frans, Hafner, Levine, Abbeel, 2024: why four sampling steps can be enough")
    fit_picture(s, jpeg(A + "diag_shortcut.png", max_w=1800, q=88), Inches(0.5), Inches(1.5), Inches(12.3), Inches(3.4))
    add_bullets(s, Inches(0.6), Inches(5.0), Inches(12.2), Inches(2.0), [
        "Add the step size d as an input: f(x(τ), τ, d) predicts the average direction over a whole jump of size d instead of only the local direction",
        "Smallest step: ordinary flow-matching loss. Larger steps: a self-consistency (bootstrap) loss; one step of size d must land where two steps of size d/2 land, and the two-step target is produced by the model itself with gradients stopped",
        "Result: 2–4 steps reach the quality of 64 in the original paper, with no separate distillation stage (one model, one training run)",
        "Dreamer 4 combines the two: per-frame τ_t from diffusion forcing plus step-size conditioning from shortcut models gives shortcut forcing, K = 4 steps per frame at 21 FPS (next slide)"], size=13.5, space=5)
    notes(s, "Shortcut models teach the network to take big steps consistently. The extra input is the step size; the extra loss says that one big step must agree with two half steps that the model computes itself. "
             "Because the target is deterministic it is easier to fit than the noisy flow-matching target, which is one reason the bootstrap term works well. Dreamer 4 combines this with diffusion forcing into shortcut forcing.")

    # 14 Shortcut forcing ---------------------------------------------------------------
    return s

def s_shortcut_forcing():
    """Shortcut forcing: the training objective"""
    s = new_slide("Shortcut forcing: the training objective", "Diffusion forcing + shortcut models, with three engineering choices that turn out to matter a lot")
    add_bullets(s, Inches(0.6), Inches(1.55), Inches(7.2), Inches(5.3), [
        "**Per-frame noise:** each frame gets an independent signal level τ_t; the model predicts frame t's clean latent from the noisy frame t, past frames, and actions",
        "**Step-size conditioning:** the network also receives d; for d > d_min the target is the *bootstrap* target: the result of two half-steps computed by the model itself (no gradient through the target)",
        "**Choice 1, x-prediction:** the network outputs the clean latent x (v-prediction would output the velocity)",
        "**Choice 2, loss in x-space:** the bootstrap target is formed in v-space (where two half-steps compose cleanly) but the loss is scaled back to x-space by (1 − τ)²",
        "**Choice 3, ramp weight:** the loss weight w(τ) = 0.9 τ + 0.1 favours high-signal (low-noise) levels, where fine detail is decided",
        "**Inference:** K = 4 steps per frame; context frames at τ_ctx ≈ 0.1; sampling stays stochastic, so RL sees diverse imagined futures"], size=14.5)
    box(s, Inches(8.1), Inches(1.6), Inches(4.7), Inches(3.05), "Effect of each piece (Table 2, FVD ↓)", [
        "Diffusion forcing, K = 64 steps:  306  (0.8 FPS)",
        "Same model, K = 4 steps:  875",
        "+ shortcut objective:  329",
        "+ x-prediction:  326",
        "+ x-space loss:  151",
        "+ ramp weight:  102",
        "Full architecture but v-space prediction/loss:  124  vs  57"], fill=PALE_BLUE, size=12.5)
    box(s, Inches(8.1), Inches(4.85), Inches(4.7), Inches(1.9), "Why this matters most", ["4 steps ≈ the quality of 16–32 diffusion-forcing steps (Fig. 8), roughly 16× fewer network evaluations per frame. That is what makes real-time interaction and large-scale imagination RL feasible."], fill=LIGHT, size=12.5)
    notes(s, "Combining the two prior ideas gets you from 875 back to 329 FVD at 4 steps. The big wins come from the parameterisation details: predicting x instead of v, computing the loss in x-space, and the ramp weight together take FVD from 329 to 102. "
             "These are the kind of choices you only discover with a careful cascade of ablations, which the paper provides.")

    # 15 Why x-prediction ---------------------------------------------------------------
    return s

def s_xpred():
    """Why x-prediction matters for autoregressive world models"""
    s = new_slide("Why x-prediction matters for autoregressive world models", "Hafner's explanation (TalkRL, Nov 2025) and the numbers")
    add_bullets(s, Inches(0.6), Inches(1.55), Inches(7.4), Inches(4.6), [
        "v-prediction carries the noise: to output v = x − ε the network must reproduce the *exact* noise pattern of its input through every layer; small mistakes in that noise become errors in the sample",
        "In autoregressive use these errors compound: each generated frame becomes context for the next, and velocity errors accumulate as drift, blur or flicker over long rollouts",
        "x-prediction is a denoising target: the network only needs to know what the clean frame should look like, so errors are pulled back toward plausible images at every step",
        "Combined with noised context (τ_ctx ≈ 0.1), the model is trained and run on slightly corrupted context, so it never sees a distribution it was not trained on",
        "Evidence: the full architecture with v-space prediction and loss reaches FVD 124; with x-prediction and x-space loss, 57 (Table 2). FVD was computed on long 384-frame generations to expose compounding error"], size=14.5)
    fit_picture(s, A + "fig8_shortcut_vs_df.png", Inches(8.3), Inches(1.6), Inches(4.5), Inches(3.9))
    caption(s, Inches(8.3), Inches(5.55), Inches(4.5), "Figure 8: FVD vs sampling steps. Shortcut forcing at 4 steps ≈ 60; diffusion forcing needs 16–32 steps to match.")
    notes(s, "This is the most transferable lesson of the paper for anyone building autoregressive generative models: predict the clean signal, not the velocity, when your own outputs become your inputs. "
             "Open Dreamer, the open-source reproduction, confirmed this independently: they report the same instability with v-prediction at scale.")

    # 16 Efficient transformer ---------------------------------------------------------------
    return s

def s_efficient():
    """Architecture choices that buy speed without losing quality"""
    s = new_slide("Architecture choices that buy speed without losing quality", "Table 2: each row adds one change to the previous row")
    fit_picture(s, A + "chart_ablation_cascade.png", Inches(0.4), Inches(1.5), Inches(8.3), Inches(4.4))
    add_bullets(s, Inches(8.9), Inches(1.55), Inches(4.1), Inches(5.4), [
        "Alternating batch lengths (64 / 256 frames): FVD 102 → 80 and a training step from 9.8 s to 1.5 s",
        "Time attention only every 4th layer: 18.9 FPS at FVD 70",
        "Grouped-query attention: 23.2 FPS, FVD unchanged",
        "Time-factorised long context trades a little quality (91) for 30 FPS; registers stabilise attention",
        "More latent tokens (128 → 256) bring FVD to 57 at 21.4 FPS, the final configuration",
        "Runs were 48 h each; FVD computed on 1,024 generations of 384 frames"], size=14)
    notes(s, "Read the bars top to bottom. The two dark bars at the top are the starting point: a diffusion-forcing transformer that is either slow or bad. The grey bars are the objective changes from the previous slides; the blue bar is the final model. "
             "The architectural changes on the lower half mostly move FPS and leave FVD alone, which is what you want.")

    # 17 Agent tokens ---------------------------------------------------------------
    return s

def s_agent_tokens():
    """From world model to agent: agent tokens & heads"""
    s = new_slide("From world model to agent: agent tokens & heads", "Phase 2: policy and reward live inside the same transformer but cannot disturb the simulation")
    add_bullets(s, Inches(0.6), Inches(1.55), Inches(7.6), Inches(5.3), [
        "**Agent tokens:** extra tokens per frame that carry a task embedding (one-hot over the 20 training tasks) and read out policy and reward",
        "**One-way attention:** agent tokens attend to actions, latents and past frames, but *nothing attends back to them*, so the world model never conditions on the policy's intentions or reward estimates",
        "**Policy head:** behavioural cloning with multi-token prediction of the next L = 8 actions; the extra horizon regularises the representation and encodes intent",
        "**Reward head:** predicts task rewards derived from game events (item obtained); a task-conditioned *scalar* reward was chosen over a reward vector so that open-vocabulary tasks remain possible",
        "**Value head:** added in Phase 3, trained by TD learning on imagined rollouts",
        "Result already at this stage: 'WM + BC' beats BC on every hard milestone (iron pickaxe 16.9 % vs 0.6 %), so the video-prediction representation is a strong prior for control"], size=14.5)
    fit_picture(s, A + "fig_rl.png", Inches(8.4), Inches(1.7), Inches(4.4), Inches(2.3))
    caption(s, Inches(8.4), Inches(4.05), Inches(4.4), "Figure 3: success rates of agents trained on the same offline data (BC, VLA, WM+BC, Dreamer 4).")
    box(s, Inches(8.4), Inches(4.7), Inches(4.4), Inches(2.0), "Why not a separate policy network?", ["Sharing the backbone gives the policy the world model's representation for free, and keeps everything one model. The one-way attention mask is what makes this safe."], fill=PALE_BLUE, size=12.5)
    notes(s, "Agent tokens are the interface between simulation and decision making. The one-directional mask is subtle but important: if latents could attend to agent tokens, the model could 'cheat' by predicting frames consistent with what the policy intends rather than with the physics of the game. "
             "Notice how much of the gain over BC comes from this phase alone; the representation matters.")

    # 18 Imagination training / PMPO ---------------------------------------------------------------
    return s

def s_pmpo():
    """Imagination training with PMPO"""
    s = new_slide("Imagination training with PMPO", "Phase 3: RL on imagined rollouts, with the transformer frozen")
    add_bullets(s, Inches(0.6), Inches(1.55), Inches(7.4), Inches(5.3), [
        "Rollouts: start from real context frames, let the policy act, and let the world model generate what happens next; rewards come from the learned reward head; γ = 0.997",
        "Frozen transformer: only the policy and value heads are trained, so the simulator cannot drift toward the policy",
        "PMPO (Abdolmaleki et al., 2024): instead of scaling the policy gradient by the advantage, use only its *sign*: positive-advantage actions are pushed up and negative ones down, with balanced weight α = 0.5 on each set",
        "Reverse KL to the frozen BC policy with β = 0.3 keeps the policy on the data manifold, like KL-regularised RLHF; it is also the main guard against exploiting world-model gaps",
        "Why not Dreamer 3's recipe? The sign-based update replaces return normalisation and the entropy bonus; it is insensitive to reward scale and copes with the extremely sparse late-game rewards",
        "Effect: iron pickaxe 16.9 % → 29.0 %, iron ingot 27.8 % → 39.5 %, diamond 0 → 0.7 %; agents also become faster (Table 8)"], size=14.5)
    fit_picture(s, A + "frame_imag_cobble.jpg", Inches(8.3), Inches(1.7), Inches(4.5), Inches(2.9))
    caption(s, Inches(8.3), Inches(4.62), Inches(4.5), "Imagined 'mine stone' rollout with reward and value traces (project page).")
    box(s, Inches(8.3), Inches(5.15), Inches(4.5), Inches(1.6), "Failure mode the KL term addresses", ["Hafner's example: the policy discovers it can 'craft' a pickaxe from invalid materials because the model renders it anyway. The KL to the BC prior limits such exploitation."], fill=LIGHT, size=12)
    notes(s, "PMPO is deliberately simple. Using only the sign of the advantage makes the update invariant to reward scale, which matters when rewards are rare item events. The KL term to the BC policy is doing two jobs: stabilising RL and preventing the policy from wandering into regions the world model gets wrong. "
             "Hafner mentioned in a talk that a few rounds of corrective online data would allow a much weaker KL, but that is not in the paper.")

    # ---- Part 3 -------------------------------------------------------------
    return s

def s_table1():
    """Is the world model accurate? Let humans play inside it"""
    # 20 Table 1 ---------------------------------------------------------------
    s = new_slide("Is the world model accurate? Let humans play inside it", "Table 1: real-time interaction on one H100; 16 tasks attempted by human testers from the same starting frame")
    rows = [["Model", "Params", "Resolution", "Context", "FPS", "Tasks solved"],
            ["MineWorld", "1.2 B", "384×224", "0.8 s", "2", "not evaluable (needs actions in advance)"],
            ["Lucid-v1", "1.1 B", "640×360", "1.0 s", "44", "0 / 16"],
            ["Oasis (small)", "500 M", "640×360", "1.6 s", "20", "0 / 16"],
            ["Oasis (large)", "—", "360×360", "1.6 s", "~5", "5 / 16"],
            ["Dreamer 4", "2 B", "640×360", "9.6 s", "21", "14 / 16"]]
    add_table(s, Inches(0.5), Inches(1.6), Inches(8.0), rows, col_widths=[1.6, 0.9, 1.35, 1.0, 0.75, 2.4], font=13, highlight_row=5, row_h=0.42)
    add_bullets(s, Inches(0.6), Inches(4.4), Inches(7.9), Inches(2.5), [
        "**The 16 tasks:** eat apple · place 3 torches · chop tree · dig 3×3 pit · craft wooden pickaxe · use furnace · place & open workbench · kill zombies · mine diamonds · complete window · place & ride boat · enter portal · place door · bed & sleep · plant reed & pour water · turn 360° & enter house",
        "The two failures were memory-related: the world changes when you look away for longer than the 9.6 s context, and inventory contents become unclear over time",
        "Genie 3 is not compared: it has no fine-grained mouse/keyboard control"], size=13.5)
    fit_picture(s, A + "fig5_human_interaction_pdf.png", Inches(8.7), Inches(1.6), Inches(4.2), Inches(2.3))
    caption(s, Inches(8.7), Inches(3.9), Inches(4.2), "Figure 5: same task, same start frame. Dreamer 4 (top) builds the wall; Lucid-v1 and Oasis do not.")
    box(s, Inches(8.7), Inches(4.6), Inches(4.2), Inches(2.1), "Why this evaluation", ["FVD and PSNR measure how video *looks*; only interaction tests whether the model got the *mechanics* right. The paper complements it with FVD on 384-frame rollouts, but there is no long-horizon *quantitative* interaction metric yet, which is a fair critique."], fill=PALE_BLUE, size=12)
    notes(s, "This is the paper's most convincing evidence about the world model. Real people sit down with a mouse and keyboard and try to do things. Dreamer 4 is the only model in which crafting, riding a boat or entering a portal work. "
             "The caveat is on the right: this is a small, human-judged protocol; I'd like to see automated long-horizon metrics in follow-ups.")

    # World-model comparison, two slides ---------------------------------------------------------------
    return s

def s_wm_compare_1():
    """Minecraft world models, stack by stack (1/2): how they are built"""
    s = new_slide("Minecraft world models, stack by stack (1/2): how they are built", "The Table 1 models compared layer by layer: provenance, data, tokenizer, backbone and objective, action interface")
    fit_picture(s, jpeg(A + "diag_wm_stack_a.png", max_w=2400, q=90), Inches(0.4), Inches(1.5), Inches(12.5), Inches(4.5))
    add_bullets(s, Inches(0.6), Inches(6.05), Inches(12.2), Inches(0.9), [
        "Two families: MineWorld predicts discrete codes with a LLaMA-style decoder that doubles as the policy; Lucid-v1, Oasis and Dreamer 4 denoise continuous latents with a transformer. Dreamer 4 adds shortcut forcing, so four passes per frame suffice, and hosts the agent heads in the same network"], size=13)
    notes(s, "Before the play-test numbers, a look at what the competitors are, layer by layer. The two extremes are MineWorld (a language-model recipe over discrete image codes, elegant because model and policy are one network, but slow) and the diffusion family, which Dreamer 4 belongs to. "
             "Within that family the differences that matter are the tokenizer capacity (Lucid squeezes a frame into about 15 tokens, Dreamer 4 keeps 256) and the training objective: rolling diffusion or plain diffusion forcing versus shortcut forcing with x-prediction. The action interface is similar across all four; that is what makes them comparable at all, and what excludes Genie 3.")
    return s

def s_wm_compare_2():
    """Minecraft world models, stack by stack (2/2): how they run"""
    s = new_slide("Minecraft world models, stack by stack (2/2): how they run", "Sampling, context, speed on one H100, the 16-task human play-test, and what each model is used for")
    fit_picture(s, jpeg(A + "diag_wm_stack_b.png", max_w=2400, q=90), Inches(0.4), Inches(1.5), Inches(12.5), Inches(3.9))
    add_bullets(s, Inches(0.6), Inches(5.5), Inches(12.2), Inches(1.45), [
        "Speed alone does not explain the results: Lucid-v1 is the fastest model in the table and solves none of the tasks; MineWorld cannot be played at all because its parallel decoding needs the actions in advance",
        "Context length does: 9.6 s versus 0.8–1.6 s is what lets the player look away and back, and the two tasks Dreamer 4 still fails are the ones that exceed that window",
        "Only Dreamer 4 is used as a training ground: the others are simulators or demos; here the same network also hosts the policy trained inside it"], size=13)
    notes(s, "Second half: how they behave at run time. Frame rate is necessary but not sufficient: Lucid is twice as fast as Dreamer 4 and fails every task, and Oasis large is the one that autocompletes buildings you never built. Context length matters more than it looks: six times more than the others, and the failures that remain are memory failures. "
             "The last row is the conceptual difference: for the other projects the simulator is the product; for Dreamer 4 it is the means, and the policy trained inside it is the result.")

    # 21 Human interaction frames ---------------------------------------------------------------
    return s

def s_interaction_frames():
    """What 'accurate object interactions' looks like"""
    s = new_slide("What 'accurate object interactions' looks like", "Frames from the project page's side-by-side human sessions (same start frame, same human inputs)")
    labels = ["Dreamer 4", "Lucid-v1", "Oasis"]; tasks = [("boat", "Place and ride boat"), ("portal", "Enter portal"), ("pickaxe", "Craft wooden pickaxe")]
    x0 = Inches(1.7); y0 = Inches(1.75); cw = Inches(3.7); ch = Inches(1.45)
    for j, lab in enumerate(labels): add_text(s, x0 + j * (cw + Inches(0.1)), Inches(1.4), cw, Inches(0.35), lab, size=14, bold=True, color=BLUE if j == 0 else GREY, align=PP_ALIGN.CENTER)
    for i, (key, name) in enumerate(tasks):
        add_text(s, Inches(0.3), y0 + i * (ch + Inches(0.1)) + Inches(0.5), Inches(1.35), Inches(0.8), name, size=12, bold=True, color=DARK)
        for j, m in enumerate(["dreamer", "lucid", "oasis"]):
            fit_picture(s, A + f"frame_{key}_{m}.jpg", x0 + j * (cw + Inches(0.1)), y0 + i * (ch + Inches(0.1)), cw, ch)
    caption_links(s, Inches(0.5), Inches(6.55), Inches(12.3), [("Single frames sampled from the project-page clips. Dreamer 4 renders the boat ride, the Nether-portal swirl and a working crafting-table menu; the baselines lose the scene or the menu.  \u25b6 All 51 clips (17 tasks \u00d7 3 models): ", None), ("danijar.com/project/dreamer4", PROJECT)])
    notes(s, "Three of the sixteen tasks. In the boat task Lucid shows only blue; in the portal task the baselines never enter; in the crafting task Dreamer 4 opens a functional crafting menu. "
             "The clips themselves are in the resource archive if you want to play them during the talk.")

    # 22 Diamond results ---------------------------------------------------------------
    return s

def s_diamond_results():
    """Offline diamond challenge: results"""
    s = new_slide("Offline diamond challenge: results", "Success rate per milestone; 1,000 episodes × 60 min; same 2,541 h of data for all methods (Table 7 / Fig. 3)")
    fit_picture(s, A + "benchmark.png", Inches(0.4), Inches(1.5), Inches(12.5), Inches(3.6))
    add_bullets(s, Inches(0.6), Inches(5.2), Inches(12.2), Inches(1.9), [
        "**Dreamer 4:** stone pickaxe 90.1 % · iron ore 66.7 % · furnace 58.1 % · iron ingot 39.5 % · iron pickaxe 29.0 % · **diamond 0.7 %** (≈ 7 of 1,000 episodes)",
        "**VLA on Gemma 3 (same data):** iron pickaxe 11.2 %, no diamonds · **BC:** 0.6 % · **VPT fine-tuned** (pretrained on 270 K h of web video): only reliably reaches sticks",
        "The gap widens along the tech tree: imitation is enough for early items; imagination RL matters where data is thin and horizons are long"], size=14)
    caption_links(s, Inches(0.5), Inches(4.95), Inches(12.3), [("Official figure from danijar.com/project/dreamer4 (benchmark.png).   \u25b6 Watch the trained agent in the real game, four uncut 60-minute evaluation episodes on YouTube: ", None), ("Uncut #1", "https://www.youtube.com/watch?v=n4SwlSrkhvU"), (" \u00b7 ", None), ("#2", "https://www.youtube.com/watch?v=5CnpLRM8iXA"), (" \u00b7 ", None), ("#3", "https://www.youtube.com/watch?v=oZyliSpRMSw"), (" \u00b7 ", None), ("#4", "https://www.youtube.com/watch?v=VSKpvb1bnbU")], size=9.5)
    notes(s, "The official results figure. Every method nails the first items; the interesting region is the right half. Dreamer 4 roughly doubles or triples the VLA on iron-age items and is the only one reaching diamonds: rarely, but from zero interaction. "
             "Remember this is a 60-minute budget per episode; humans need about 20 minutes on average.")

    # 23 Agent ablations + time ---------------------------------------------------------------
    return s

def s_ablations():
    """Where do the gains come from? Agent ablations and speed"""
    s = new_slide("Where do the gains come from? Agent ablations and speed", "Figure 4 / Table 8: representation (WM+BC vs BC) and imagination RL (Dreamer 4 vs WM+BC) both contribute")
    fit_picture(s, A + "chart_table7_hard.png", Inches(0.4), Inches(1.5), Inches(7.4), Inches(3.4))
    fit_picture(s, A + "chart_time_to_milestone.png", Inches(8.0), Inches(1.5), Inches(4.9), Inches(3.4))
    add_bullets(s, Inches(0.6), Inches(5.05), Inches(12.2), Inches(2.0), [
        "**Representation:** BC on the world model's features (WM+BC) vs plain BC: iron pickaxe 16.9 % vs 0.6 %; the authors: 'video prediction implicitly learns an understanding of the world that is useful for decision making'",
        "**Imagination RL:** adds +12 pts on iron pickaxe and +12 pts on iron ingot over WM+BC, and unlocks diamonds",
        "**Speed:** Dreamer 4 is fastest at every milestone: iron pickaxe in 13.3 min vs 31.1 min for the VLA; diamonds in 20.7 min on average when achieved (human average ≈ 20 min)",
        "Task input matters: BC without the task embedding collapses to 8.8 % stone pickaxe (Table 7)"], size=13.5)
    notes(s, "Two separable effects. Using the world model as the representation for imitation already gives a large jump, which is a statement about video pretraining. RL inside the model then adds a smaller but consistent gain on the hardest items and makes the agent faster, which is typical of RL over imitation.")

    # 24 Label efficiency ---------------------------------------------------------------
    return s

def s_label_efficiency():
    """Unlabeled video: how many action labels are needed?"""
    s = new_slide("Unlabeled video: how many action labels are needed?", "Figure 7: action conditioning from a small labeled fraction, and transfer to unseen visual domains")
    fit_picture(s, A + "fig7_action_generalization.png", Inches(0.4), Inches(1.5), Inches(8.2), Inches(2.9))
    add_bullets(s, Inches(0.6), Inches(4.55), Inches(12.2), Inches(2.4), [
        "**Setup:** train on all 2,541 h of video, but keep actions for only a subset; measure PSNR/SSIM of action-conditioned predictions, normalised between 'no actions' (0 %) and 'all actions' (100 %)",
        "10 h of labels → 53 % PSNR / 75 % SSIM; 100 h → 85 % / 100 %; 1,000 h → 100 %. Action understanding saturates with roughly 4 % of the data labeled",
        "**Domain transfer:** with actions only from the Overworld, predictions in the Nether/End (seen unlabeled) recover 76 % / 80 %, so the model separates 'what actions do' from 'what the world looks like'",
        "Why it matters: this is the road to internet-scale video pretraining, where labels are scarce (VPT needed an inverse-dynamics model for this)"], size=14)
    box(s, Inches(8.9), Inches(1.6), Inches(4.0), Inches(2.7), "Mechanism", ["Unlabeled frames receive a learned 'no action' embedding; the dynamics loss is the same. The model therefore learns visual dynamics from everything and the action mapping from the labeled slice."], fill=PALE_BLUE, size=12.5)
    notes(s, "This experiment is easy to overlook, but it matters for the scaling story. Only about a hundred hours of labeled actions are needed on top of thousands of unlabeled hours, and the learned action semantics transfer to visual domains that were never labeled. "
             "That is the argument for scaling to internet video later.")

    # 25 Imagination rollouts (Fig 1) ---------------------------------------------------------------
    return s

def s_fig1_rollouts():
    """Inside the imagination: decoded training rollouts"""
    s = new_slide("Inside the imagination: decoded training rollouts", "Figure 1: imagined sequences for four agent tasks, decoded only for visualisation")
    fit_picture(s, jpeg(A + "fig1_teaser_pdf.png"), Inches(0.5), Inches(1.5), Inches(8.6), Inches(5.2))
    add_bullets(s, Inches(9.3), Inches(1.6), Inches(3.7), Inches(5.3), [
        "The world model simulates chopping, crafting menus, mining, cave lighting and diamond ore; all of it is generated, none recorded",
        "RL never sees pixels: it operates on latents; decoding is for us",
        "Each rollout starts from real context frames and follows the *current* policy, so training data stays on-policy without touching the game",
        "Stochastic sampling gives diverse futures, useful for exploring rare outcomes such as finding ore"], size=14)
    caption_links(s, Inches(0.5), Inches(6.62), Inches(8.6), [("\u25b6 The official video (slide 4, 2:55) shows these rollouts in motion: ", None), ("youtube.com/watch?v=oDlBtTcX0g0", YT)], size=10)
    notes(s, "Figure 1 from the paper. All of these frames are generated by the model while the policy is being trained. Worth stressing to a mixed audience: the agent learns in latent space; decoding is purely for visualisation.")

    # 26 Beyond Minecraft ---------------------------------------------------------------
    return s

def s_beyond_minecraft():
    """Beyond Minecraft: robotics & egocentric video (qualitative)"""
    s = new_slide("Beyond Minecraft: robotics & egocentric video (qualitative)", "Figures 6 and 9: same recipe, different data; no quantitative benchmark yet")
    fit_picture(s, jpeg(A + "fig6_robotics.png"), Inches(0.4), Inches(1.5), Inches(8.4), Inches(3.2))
    caption(s, Inches(0.4), Inches(4.7), Inches(8.4), "Figure 6: SOAR robot-arm data; counterfactual actions (pick objects, flip bowl, press ball, move towel, throw bowl) rendered by the world model.")
    fit_picture(s, A + "frame_realworld_soar1.jpg", Inches(9.0), Inches(1.5), Inches(3.9), Inches(2.3))
    caption(s, Inches(9.0), Inches(3.82), Inches(3.9), "Project page: human counterfactual interaction with the robot world model.")
    add_bullets(s, Inches(0.6), Inches(5.2), Inches(12.2), Inches(1.9), [
        "**SOAR:** 180 h of teleoperation + online-RL data, 256×256 at 5 FPS, 7-D relative end-effector actions; N_z = 512, context 96 frames",
        "**Epic Kitchens 100:** 100 h of egocentric kitchen video, no actions; generations from held-out context (Fig. 9) show the recipe works on real, unstructured video",
        "**Caveat:** no policy was trained and no metrics are reported for these domains; they show generality of the world model, not of the agent"], size=14)
    notes(s, "The paper positions Dreamer 4 as a step toward robotics. The evidence here is qualitative: plausible counterfactual generations on real robot and kitchen video. Hafner left DeepMind shortly after the paper to work on humanoid robotics, which tells you where the authors think this goes.")

    # 27 Dreamer 3 vs 4 ---------------------------------------------------------------
    return s

def s_d3_vs_d4():
    """Dreamer 3 vs Dreamer 4"""
    s = new_slide("Dreamer 3 vs Dreamer 4", "Appendix F: what changed, and what the higher-fidelity model costs")
    rows = [["", "Dreamer 3 (Nature 2025)", "Dreamer 4"],
            ["World model", "RSSM (recurrent + variational latent)", "Block-causal diffusion/flow transformer, shortcut forcing"],
            ["Minecraft input", "64×64 pixels + inventory state; abstract crafting actions", "360×640 pixels only; raw mouse & keyboard"],
            ["Data", "1.4 K h of *online* interaction, no human data", "2.5 K h of *offline* human data, no interaction"],
            ["RL", "Return normalisation + entropy bonus", "PMPO (advantage sign) + KL to BC prior"],
            ["Speed", "~1,000× faster than a diffusion transformer", "~30× faster than diffusion forcing; ~40× slower than the RSSM"]]
    add_table(s, Inches(0.5), Inches(1.55), Inches(7.6), rows, col_widths=[1.5, 3.0, 3.1], font=12.5, highlight_col=2, row_h=0.74)
    fit_picture(s, jpeg(A + "fig11_dreamer3_vs_4.png"), Inches(8.4), Inches(1.55), Inches(4.5), Inches(1.9))
    caption(s, Inches(8.4), Inches(3.5), Inches(4.5), "Figure 11: multi-step generations, Dreamer 4 (top) vs Dreamer 3 (bottom).")
    fit_picture(s, A + "chart_speed.png", Inches(8.3), Inches(3.95), Inches(4.7), Inches(2.6))
    caption(s, Inches(8.4), Inches(6.5), Inches(4.5), "Generation speed on a log scale (paper, TalkRL): ~30× faster than diffusion forcing, ~40× slower than the RSSM.", size=9.5)
    notes(s, "Same family, different regime. Dreamer 3 solved diamonds with online interaction and privileged state at 64×64; Dreamer 4 does it offline from raw pixels and inputs. The price is speed: the transformer is still about forty times slower than the recurrent model, according to Hafner.")

    # 28 Compute & data ---------------------------------------------------------------
    return s

def s_compute():
    """Data, compute and scale"""
    s = new_slide("Data, compute and scale", "Appendix A and Table 3")
    rows = [["Dataset", "Size", "Resolution / FPS", "Actions", "Dynamics config"],
            ["Minecraft (VPT contractor 6–10)", "2,541 h", "360×640 → 384×640 padded, 20 FPS", "23 keys + 121-way mouse; item events → rewards", "N_z 256 · C 192 · T 64/256"],
            ["Overworld vs Nether/End split", "subset", "same", "labels only for Overworld", "action-generalisation study"],
            ["SOAR robotics", "180 h", "256×256, 5 FPS", "7-D relative end-effector", "N_z 512 · C 96 · T 32/128"],
            ["Epic Kitchens 100", "100 h", "256×256, 10 FPS", "none", "same as SOAR"]]
    add_table(s, Inches(0.5), Inches(1.55), Inches(12.3), rows, col_widths=[2.6, 1.0, 2.9, 3.2, 2.6], font=12, row_h=0.5)
    rows2 = [["Agent (Table 3)", "Human data", "Web video", "Online interaction"],
             ["VPT (RL fine-tuned)", "2.5 K h", "270 K h", "194 K h"],
             ["VPT (BC)", "2.5 K h", "270 K h", "—"],
             ["Dreamer 3", "—", "—", "1.4 K h"],
             ["Dreamer 4", "2.5 K h", "—", "—"]]
    add_table(s, Inches(0.5), Inches(4.35), Inches(6.6), rows2, col_widths=[2.2, 1.4, 1.4, 1.6], font=12, highlight_row=4, row_h=0.4)
    add_bullets(s, Inches(7.4), Inches(4.4), Inches(5.5), Inches(2.6), [
        "**Compute:** 256–1,024 TPU v5p chips per run (exact chip-hours not disclosed)",
        "**Ablations:** 48 h runs per configuration",
        "**Model:** ≈ 2 B parameters total; inference 21 FPS on one H100",
        "**Not released:** code, weights or data recipe (Hafner: 'probably not'); reproductions exist (Open Dreamer, Dreamer-MC, Hansen's PyTorch port)"], size=13.5)
    notes(s, "Scale context. The Minecraft data is the public VPT contractor set, which makes the comparison with VPT clean: Dreamer 4 uses about a hundred times less data and no interaction. Compute is disclosed only as a TPU range. Nothing was open-sourced, which shaped the follow-up ecosystem.")

    # ---- Part 4 -------------------------------------------------------------
    return s

def s_limitations():
    """Limitations the paper itself states"""
    # 30 Limitations ---------------------------------------------------------------
    s = new_slide("Limitations the paper itself states", "From the discussion section and the authors' talks")
    numbered(s, Inches(0.6), Inches(1.65), Inches(12.1), [
        ("Diamonds are rare:", "0.7 % success; the authors call the pipeline a 'reliable and performant starting point', not a solved task"),
        ("Memory:", "9.6 s of context; walk into a house for 30 s and the outside is regenerated. Long-term memory is the first item on the authors' roadmap"),
        ("Inventory drift:", "small UI elements and item counts blur over long horizons; small objects and long-range semantic correlations are what video models learn last"),
        ("Frozen, exploitable simulator:", "no epistemic-uncertainty estimate; the policy can exploit model errors (invalid crafting), currently mitigated only by the KL constraint"),
        ("Two-stage training:", "tokenizer is trained separately and frozen; the authors expect end-to-end training eventually"),
        ("Single domain for the agent:", "RL results exist only for Minecraft; robotics and kitchen video are qualitative world-model demos"),
        ("Compute:", "hundreds of TPU v5p chips per run; not a recipe individuals can reproduce at full scale")], size=15.5, gap=0.2, num_w=0.6)
    notes(s, "The authors are quite candid. The two that matter most for the agenda of the paper are memory and exploitability: both limit how far imagination training can be pushed before the policy learns things that are only true inside the model.")

    # 31 Critical reading ---------------------------------------------------------------
    return s

def s_critical():
    """A critical reading: established vs. open"""
    s = new_slide("A critical reading: established vs. open", "What a reviewer would push on (and what independent groups later found)")
    columns(s, Inches(1.6), Inches(5.2), [("Well supported", ["Shortcut forcing + x-prediction gives a large speed/quality win: a clean 12-step ablation cascade, reproduced by Open Dreamer at 1.6 B scale (JAX, 2026).",
        "The world model handles object interactions far better than Oasis / Lucid-v1: consistent human play-tests plus long-rollout FVD.",
        "World-model features are a strong prior for imitation (WM+BC ≫ BC on the same data).",
        "Action conditioning from ~4 % labeled data works and transfers across visual domains."]), ("Open or thinly supported", ["Diamond result: 0.7 % without confidence intervals or per-seed variance; success criterion is a game event, protocol details are in the appendix only.",
        "No direct quantitative long-horizon accuracy metric; interaction accuracy is human-judged on 16 tasks (Pith/EmergentMind critique).",
        "RL gains over WM+BC are modest on most items; small-scale reproductions report high seed variance in the RL phase and reward-hacking of the frozen reward head.",
        "No peer review as of Sept 2026 (arXiv v1 only); no code or weights; nobody outside DeepMind has reproduced offline diamonds.",
        "Generality of the *agent* beyond Minecraft is untested."])], numerals=False, bullets=True, size=14.5, head_size=16, rule_colors=[GREEN, AMBER], gap=Inches(0.6))
    notes(s, "Balance sheet. The methodological contribution (how to make a fast, accurate autoregressive video world model) is solid and has been independently reproduced. The headline agent result is real but statistically thin and has not been reproduced outside DeepMind. "
             "For a reading group, this split is where the discussion usually starts.")

    # Genie 3 context, two slides ---------------------------------------------------------------
    return s

def s_genie3_1():
    """Genie 3 (1/2): what is public"""
    s = new_slide("Genie 3 (1/2): what is public", "Google DeepMind, Aug 2025; blog post and model page only. Plain boxes = stated; amber = inferred from the Genie 2 recipe; grey = undisclosed")
    fit_picture(s, jpeg(A + "genie3_top.png", max_w=2400, q=90), Inches(0.4), Inches(1.55), Inches(12.5), Inches(3.4))
    add_bullets(s, Inches(0.6), Inches(5.2), Inches(12.2), Inches(1.7), [
        "A different problem: any text-prompted world, 24 FPS at 720p, about a minute of visual memory, navigation-level actions, versus one game, full mouse and keyboard, 9.6 s of context at 21 FPS and 360p",
        "Why the paper cannot compare (§4.2): Genie 3 exposes only camera actions and one generic 'interact' button, so the 16 Minecraft tasks are not expressible; nothing about its size, data or objective is published, and the '11 B / 200k hours' figures that circulate are Genie 1's"], size=13)
    notes(s, "People will ask about Genie 3, so here is what is known. Everything in the plain boxes is stated by DeepMind: auto-regressive frame-by-frame generation conditioned on the prompt, the latest actions and the whole trajectory so far, with 3D consistency that is emergent rather than explicit. The amber pipeline is the recipe DeepMind published for Genie 2, a reasonable guess for Genie 3 but not confirmed. "
             "Parameter count, tokenizer, data and objective are undisclosed; there is no paper. The Dreamer 4 authors say why they do not compare: Genie 3's action space is navigation plus one interact button, and the Minecraft tasks need menus and precise mouse input.")
    return s

def s_genie3_2():
    """Genie 3 (2/2): in use, and where Dreamer 4 differs"""
    s = new_slide("Genie 3 (2/2): in use, and where Dreamer 4 differs", "Human play in the research preview and Project Genie, the SIMA 2 agent loop, stated limitations")
    fit_picture(s, jpeg(A + "genie3_bottom.png", max_w=2400, q=90), Inches(0.4), Inches(1.55), Inches(12.5), Inches(2.75))
    add_bullets(s, Inches(0.6), Inches(4.5), Inches(12.2), Inches(2.45), [
        "Agent outside vs. agent inside: SIMA 2 acts in Genie 3 worlds with Gemini-written tasks and a learned reward model, and Genie 3 only renders the consequences; Dreamer 4's policy is a head on the same transformer, trained by RL on imagined latents with the reward head it learned from the data",
        "Same limits, different scale: both are closed. Genie 3 stays consistent for minutes but with a limited action space; Dreamer 4 forgets beyond 9.6 s but simulates crafting menus, furnaces, boats and portals from raw mouse and keyboard",
        "Convergent direction: both bet on world models as training grounds, Genie 3 via generated worlds for embodied agents and robots, Dreamer 4 via imagination training on offline video; neither has yet shown a policy that transfers to a physical robot"], size=13)
    notes(s, "Bottom half of the Genie 3 picture. The interesting contrast is architectural: in DeepMind's own SIMA 2 work the agent, its rewards and its learning all live outside the world model, which is just an environment. In Dreamer 4 the policy is part of the world-model transformer and is trained on the model's latents, never on pixels. "
             "Both approaches are closed and both point the same way, toward world models as the place where agents get their experience, but they trade off breadth against precision: Genie 3 generalises across worlds with a coarse action space, Dreamer 4 masters one world with the full human interface.")

    # 32 Future directions ---------------------------------------------------------------
    return s

def s_future():
    """Where the authors want to take it"""
    s = new_slide("Where the authors want to take it", "Future work listed in the paper and expanded in the TalkRL interview (Nov 2025)")
    items = [("Internet-video pretraining", "Learn dynamics from unlabeled web video; label only a small slice with actions (Fig. 7 is the proof of concept)."),
             ("Long-term memory", "Beyond 9.6 s: retrieval or compressed memory so the world stays consistent when you look away."),
             ("Language conditioning", "Replace one-hot task IDs with text embeddings; scalar task-conditioned reward already anticipates open-vocabulary tasks."),
             ("A little online data", "Small rounds of *corrective* interaction to fix the errors the policy exploits; then the KL constraint can be relaxed."),
             ("Automatic goal discovery", "Empowerment / exploration objectives (APD, Plan2Explore, Director) so agents propose their own tasks inside the model."),
             ("End-to-end training", "Fold the tokenizer into the dynamics model; scale parameters and context together.")]
    columns(s, Inches(1.55), Inches(2.55), items[:3], size=14, head_size=15.5)
    columns(s, Inches(4.35), Inches(2.55), items[3:], start=4, size=14, head_size=15.5)
    notes(s, "Six directions; three of them (memory, corrective data and language) directly address the limitations we just discussed. The authors' next steps are toward physical robots, not more Minecraft.")

    # 33 Takeaways ---------------------------------------------------------------
    return s

def s_takeaways():
    """Takeaways"""
    s = new_slide("Takeaways")
    tk = [("Imagination training works offline, from pixels", "Dreamer 4 reaches diamonds in Minecraft with zero environment interaction and about 100× less data than VPT."),
          ("The enabling contribution is speed at quality", "Shortcut forcing (4 sampling steps), x-prediction with an x-space loss, and time attention only in every 4th layer: 21 FPS on one GPU with a 9.6 s context."),
          ("The bar is interaction accuracy, not visual polish", "Validated by humans playing inside the model: 14 of 16 tasks, against 5 of 16 for the best prior Minecraft world model."),
          ("Video pretraining is a strong prior for control", "Most of the gain over BC comes from the world-model representation; RL adds the rest on the hardest, longest-horizon items."),
          ("Action labels are cheap", "About 100 h of labeled actions on top of thousands of unlabeled hours suffice, and action semantics transfer to unseen visual domains."),
          ("Open problems remain", "Short memory, exploitable frozen simulators, thin statistics on the headline result, and no official code or weights.")]
    columns(s, Inches(1.55), Inches(2.6), tk[:3], size=14.5, head_size=15.5, head_h=0.72)
    columns(s, Inches(4.4), Inches(2.6), tk[3:], start=4, size=14.5, head_size=15.5, head_h=0.72)
    notes(s, "Six takeaways, ordered from result to method to caveats.")

    # 34 Discussion questions ---------------------------------------------------------------
    return s

def s_questions():
    """Questions for discussion"""
    s = new_slide("Questions for discussion")
    numbered(s, Inches(0.7), Inches(1.7), Inches(11.9), [
        "How much of the diamond result is the world model versus PMPO? Would a stronger offline-RL baseline on world-model features (no imagination) close the gap?",
        "Is human play-testing on 16 tasks a sufficient measure of 'accurate simulation'? What automated long-horizon metric would you propose?",
        "The transformer is frozen during RL and the reward head is learned: where would you expect exploitation to appear first, and how would you detect it offline?",
        "9.6 s of context: which memory mechanism (retrieval, state-space layers, compressed summaries) fits a block-causal diffusion transformer best?",
        "The recipe needs ~100 h of action labels per domain. What does the path to internet-scale video look like: inverse dynamics models, or Dreamer 4's 'no-action' embedding at scale?",
        "What would convince you that this transfers to real robots, and what evaluation would you run first?"], size=16, gap=0.3, num_w=0.65)
    notes(s, "Pick two or three depending on the room.")

    # 35 References ---------------------------------------------------------------
    return s

def s_references():
    """References & resources"""
    s = new_slide("References & resources")
    add_bullets(s, Inches(0.6), Inches(1.5), Inches(12.3), Inches(5.6), [
        "**Paper:** Hafner*, Yan*, Lillicrap. Training Agents Inside of Scalable World Models. arXiv:2509.24527 (29 Sep 2025). https://arxiv.org/abs/2509.24527",
        "**Project page & videos:** https://danijar.com/project/dreamer4/ (overview video youtube.com/watch?v=oDlBtTcX0g0, four uncut 60-min 'Diamond Challenge' evaluation episodes, 51 human-interaction clips)",
        "**Authors in conversation:** TalkRL E73 'Danijar Hafner on Dreamer v4' (10 Nov 2025), transcript available; Hack Club AMA (Dec 2025)",
        "**Ingredients:** Chen et al., Diffusion Forcing (2407.01392) · Frans, Hafner, Levine, Abbeel, Shortcut Models (2410.12557) · Chen et al., MAETok (2502.03444) · Baker et al., VPT (2206.11795) · Hafner et al., DreamerV3 (2301.04104)",
        "**Independent reproductions / follow-ups:** next-state/open-dreamer (JAX, 1.6 B Minecraft world model, Jul 2026) · IamCreateAI/Dreamerv4-MC (weights on HF) · nicklashansen/dreamer4 & MMBench2 (Hansen & Wang, 2606.27326) · lucidrains/dreamer4 (PyTorch)",
        "**Everything above, archived:** https://github.com/HarmannBitte/Dreamer-4 (PDFs, repo snapshots, articles, transcripts, the official clips used in this deck, and a MEDIA_INDEX.md)"], size=14, space=9)
    notes(s, "All sources, plus the GitHub archive that contains local copies of every item used to build this deck.")

    # ---- Appendix -------------------------------------------------------------
    return s

def s_appx_config():
    """Appendix A: Configuration and hyper-parameters"""
    s = new_slide("Appendix A: Configuration and hyper-parameters")
    rows = [["Component", "Setting"],
            ["Tokenizer", "Masked autoencoder; 16×16 patches; patch dropout ~ U(0, 0.9); loss MSE + 0.2·LPIPS; bottleneck 512×16 with tanh → N_z = 256 tokens × 32 dims; causal in time; ≈ 400 M params; frozen after pretraining"],
            ["Dynamics model", "≈ 1.6 B params; pre-RMSNorm, RoPE, SwiGLU, QK-norm, logit soft-capping, register tokens; space attention in 3/4 layers, causal time attention every 4th layer; GQA; context C = 192 frames (9.6 s); alternating batch lengths T1/T2 = 64/256"],
            ["Shortcut forcing", "per-frame signal level τ, step size d; x-prediction; bootstrap target formed in v-space, loss scaled to x-space by (1−τ)²; ramp weight w(τ) = 0.9τ + 0.1; K = 4 sampling steps; context noise τ_ctx ≈ 0.1"],
            ["Actions", "23 binary keys + 121-way mouse (μ-law, 11×11 foveated bins, VPT convention); learned 'no action' embedding for unlabeled video"],
            ["Agent (phase 2)", "agent tokens with one-hot task (20 tasks), one-way attention; BC with multi-token prediction L = 8; task-conditioned scalar reward head; data mix 50 % uniform / 50 % task-relevant"],
            ["Imagination RL (phase 3)", "transformer frozen; policy + TD value heads; PMPO with advantage sign, α = 0.5, reverse-KL β = 0.3 to frozen BC policy; γ = 0.997"],
            ["Evaluation", "1,000 episodes × 60 min, empty inventory, random worlds, fixed prompt sequence; human interaction: 16 tasks on one H100 at 21 FPS"],
            ["Compute / data", "256–1,024 TPU v5p; 2,541 h VPT contractor video (subsets 6–10), 90/10 split by 5-min chunk; ablations: 48 h runs, FVD on 1,024 × 384-frame generations"]]
    add_table(s, Inches(0.5), Inches(1.45), Inches(12.3), rows, col_widths=[2.1, 10.2], font=11, row_h=0.6)
    notes(s, "Reference slide; not meant to be presented in full.")
    return s

def s_appx_table2():
    """Appendix B: Full design cascade (Table 2)"""
    s = new_slide("Appendix B: Full design cascade (Table 2)")
    rows = [["Change (cumulative)", "FPS", "FVD ↓"], ["Diffusion-forcing transformer, K = 64", "0.8", "306"], ["K = 4 sampling steps", "9.1", "875"], ["+ shortcut objective (→ shortcut forcing)", "", "329"], ["+ x-prediction", "", "326"], ["+ x-space loss", "", "151"], ["+ ramp weight", "", "102"], ["+ alternating batch lengths (step 9.8 s → 1.5 s)", "", "80"], ["+ long context only every 4th layer", "18.9", "70"], ["+ grouped-query attention", "23.2", "71"], ["+ time-factorised long context", "30.1", "91"], ["+ register tokens", "", "91"], ["N_z 128 → 256 (final)", "21.4", "57"], ["(reference) full architecture, v-space prediction & loss", "", "124"]]
    add_table(s, Inches(0.5), Inches(1.45), Inches(7.5), rows, col_widths=[5.3, 1.0, 1.2], font=11.5, highlight_row=12, row_h=0.36)
    add_bullets(s, Inches(8.3), Inches(1.6), Inches(4.6), Inches(4.5), ["48-hour training runs per row", "FVD on 1,024 generations of 384 frames (long rollouts to expose compounding error)", "FPS measured for generation on one H100 where reported", "Fig. 8 adds the steps sweep: shortcut forcing FVD ≈ 160/85/60/50 at 1/2/4/8 steps vs ≈ 1,020/830/530/220 for diffusion forcing"], size=13.5)
    notes(s, "Numbers transcribed from Table 2 and read off Figure 8.")
    return s

def s_appx_table7():
    """Appendix C: Full success-rate table (Table 7, %)"""
    s = new_slide("Appendix C: Full success-rate table (Table 7, %)")
    rows = [["Milestone", "VPT (ft)", "BC (no task)", "BC", "VLA (Gemma 3)", "WM + BC", "Dreamer 4"],
            ["Log", "84.3", "71.4", "97.3", "98.5", "99.6", "99.1"], ["Planks", "65.3", "68.6", "95.7", "98.3", "99.6", "98.9"], ["Crafting table", "4.7", "63.8", "93.5", "97.2", "99.1", "98.5"], ["Stick", "52.6", "62.4", "95.0", "97.7", "98.9", "98.7"],
            ["Wooden pickaxe", "0.0", "33.8", "86.5", "94.1", "97.3", "96.6"], ["Cobblestone", "6.9", "32.0", "83.9", "91.6", "97.2", "95.9"], ["Stone pickaxe", "0.0", "8.8", "53.8", "76.7", "89.4", "90.1"], ["Iron ore", "0.1", "3.6", "26.5", "46.3", "62.9", "66.7"],
            ["Furnace", "0.0", "4.0", "16.2", "42.4", "51.1", "58.1"], ["Iron ingot", "0.1", "0.2", "4.3", "22.5", "27.8", "39.5"], ["Iron pickaxe", "0.0", "0.0", "0.6", "11.2", "16.9", "29.0"], ["Diamond", "0.0", "0.0", "0.0", "0.0", "0.0", "0.7"]]
    add_table(s, Inches(0.5), Inches(1.45), Inches(12.3), rows, col_widths=[2.3, 1.5, 1.7, 1.4, 2.0, 1.6, 1.8], font=12, highlight_col=6, row_h=0.38)
    caption(s, Inches(0.5), Inches(6.5), Inches(12), "1,000 evaluation episodes of 60 minutes each; all agents trained on the same 2,541 h of contractor data (VPT additionally pretrained on 270 K h of web video).")
    notes(s, "Full table for reference.")
    return s

def s_appx_glossary():
    """Appendix D: Glossary"""
    s = new_slide("Appendix D: Glossary")
    rows = [["Term", "Meaning in this paper"],
            ["World model", "Learned model that predicts future observations (here: latent frames) given past observations and actions"],
            ["Imagination training", "Training the policy on rollouts generated by the world model instead of the real environment"],
            ["Tokenizer / latents", "Encoder–decoder mapping each frame to 256 continuous tokens the dynamics model operates on"],
            ["Block-causal attention", "Full attention within a frame, causal across frames; enables frame-by-frame online generation"],
            ["Diffusion forcing", "Diffusion training with an independent noise level per frame in a sequence"],
            ["Shortcut model", "Diffusion/flow model conditioned on step size, trained to be self-consistent across step sizes, which allows few-step sampling"],
            ["x- vs v-prediction", "Network predicts the clean latent (x) vs the velocity x − ε (v); Dreamer 4 uses x-prediction"],
            ["FVD / PSNR / SSIM", "Fréchet Video Distance (distribution-level video quality, lower is better) / per-frame reconstruction fidelity metrics"],
            ["GQA, RoPE, registers", "Grouped-query attention (fewer KV heads), rotary position embeddings, extra learnable tokens that absorb attention mass"],
            ["BC, VLA, PMPO", "Behavioural cloning; vision-language-action model (here built on Gemma 3); the sign-based, KL-regularised policy-gradient update used for RL"]]
    add_table(s, Inches(0.5), Inches(1.45), Inches(12.3), rows, col_widths=[2.4, 9.9], font=11.5, row_h=0.45)
    notes(s, "Glossary for the mixed audience.")
    return s

