"""Phase 3 -- PMPO reinforcement learning for the policy, entirely in imagination.

    Phase 3: Imagination Training -- Optimize policy head using (11) and value head using (10) on
    trajectories generated by the world model and the policy head.        (paper Algorithm 1)

Input: the phase-1 world model (``--dyn``, which names the dataset and the tokenizer) and a
phase-2 checkpoint (``--init_from``), which supplies the finetuned transformer, the agent heads, the
frozen behavioral prior and the frozen reward head. The checkpoints written here carry the same
things, so a run can also be continued from one of its own. No environment is stepped during
training.

One network does everything, as in the paper: the transformer phase 2 finetuned is what the agent
heads READ and what GENERATES the next imagined frame.

The policy, reward and value heads sit on AGENT tokens inside the dynamics transformer
(:mod:`dreamer4.models.agent_heads`). The transformer is FROZEN here -- "We only update the policy
and value heads and keep the transformer frozen" (Section 3.3) -- so a rollout buffers the agent
embeddings ``h_t`` it produced and the update re-runs only the heads over them. The value head is a
symexp two-hot distribution trained by cross-entropy on the lambda-return (Eq. 10); the policy is
trained with PMPO (Eq. 11): the sign of the advantage, ``alpha`` between the positive and negative
sets, and a fixed ``beta`` on the reverse KL to the behavioral prior.

    * a dream ENDS when the reward head says it ended, through the dataset's own terminal rule
      applied to the head's distribution (``terminal_bins``);
    * the reward is the head's, not the task's arithmetic -- nothing here knows what the
      environment pays;
    * dreams start from recorded CONTEXTS (:class:`DemoStarts`) -- "Imagined rollouts start from
      contexts of the dataset that was used during the earlier training phases" -- one rollout per
      context;
    * evaluation is always the REAL environment, every ``--eval_every`` steps, and it is what
      selects ``best.pt``.

Writes to ``--out``: ``config.json``, ``metrics.jsonl``, ``checkpoints/{latest,best}.pt``,
``final.json`` and TensorBoard scalars under ``tb/``. A rerun into the same ``--out`` REPLACES all
of them.

    python -m dreamer4.train.train_pmpo --dyn <phase-1 ckpt> \\
        --init_from runs/heads/checkpoints/best.pt --out runs/rl --K 1 --steps 3200
"""
import argparse
import copy
import json
import time
from pathlib import Path

import numpy as np
import torch
from torch.utils.tensorboard import SummaryWriter

from dreamer4.agent_eval import evaluate, make_env
from dreamer4.models.agent_heads import build_agent_heads, terminal_bins
from dreamer4.models.world_model import (AgentPolicy, WorldModel, dream_context,
                                         dream_step, window_frames)
from dreamer4.train.pmpo_objectives import compute_lambda_returns, pmpo_coeffs


class DemoStarts:
    """The contexts dreams start from, read from the recorded episodes.

    Paper Section 3.3: "Imagined rollouts start from contexts of the dataset that was used during
    the earlier training phases. Unlike previous generations of Dreamer, we start only one rollout
    from each context." A context here is a whole window ending at a recorded frame, built by the
    convention in :mod:`dreamer4.models.world_model` -- so a dream begins with the same kind of
    history the policy was trained on and will meet at evaluation. The window carries
    ``tokenizer.history - 1`` extra leading frames, so the tokenizer encodes its first slot from the
    frames that really preceded it. Contexts are drawn uniformly over all recorded frames.
    """

    def __init__(self, dataset, *, window, history, rng=None):
        self.window = int(window)
        self.span = int(window) + int(history) - 1
        self.n_actions = int(dataset.action_dim)
        frames, proprio, into, task, local = [], [], [], [], []
        offset = 0
        for i in range(len(dataset)):
            n = dataset.episode_frames(i)
            clip = dataset.clip(i, 0, n)
            # The last frame of an episode that ENDED is not a start: there is nothing left to do
            # from it.
            keep = n - 1 if "terminals" in clip and bool(clip["terminals"][-1]) else n
            if keep <= 0:
                continue
            frames.append(clip["video"][:n])
            proprio.append(clip["proprio"][:n].astype(np.float32))
            led = np.full(n, -1, np.int64)                  # action that led INTO each frame
            led[1:] = clip["actions"][:n - 1].argmax(-1)
            into.append(led)
            # The paper's task indicator, recorded per episode by a multi-task collector.
            task.append(np.full(n, int(dataset.episode_meta(i).get("task", 0)), np.int64))
            local.append((offset, keep))
            offset += n
        self.frames = np.concatenate(frames)
        self.proprio = np.concatenate(proprio)
        self.into = np.concatenate(into)
        self.task = np.concatenate(task)
        # Global index of every legal start, and the episode offset it belongs to, so a window can
        # be clamped at its own episode's first frame rather than the array's.
        self.index = np.concatenate([np.arange(o, o + k) for o, k in local])
        self.base = np.concatenate([np.full(k, o) for o, k in local])
        self.rng = rng or np.random.default_rng(0)

    def sample(self, n):
        """``n`` contexts. Returns the encode window, its proprio, its aligned actions and task."""
        pick = self.rng.choice(len(self.index), n)
        end = self.index[pick]
        base = self.base[pick]
        slots = window_frames(end - base, self.span) + base.reshape(-1, 1)
        win = slots[:, -self.window:]
        led = self.into[win]
        aligned = np.zeros((n, self.window, self.n_actions + 1), np.float32)
        fresh = np.ones_like(win, bool)
        fresh[:, 1:] = win[:, 1:] != win[:, :-1]
        fresh[:, 0] = False                            # slot 0 always carries the start flag
        fresh &= led >= 0
        rows, cols = np.nonzero(fresh)
        aligned[rows, cols, led[rows, cols]] = 1.0
        aligned[~fresh, -1] = 1.0
        return {"encode": self.frames[slots], "proprio": self.proprio[win],
                "actions": aligned, "task": self.task[end]}


class Tape:
    """The per-episode buffers a dream fills, and the masks the update reads them through.

    ``continues`` and ``alive`` are the only two the losses ever index by: ``alive[:, t]`` marks a
    state the policy really occupied, ``continues[:, t]`` is the ``c_t`` of Eq. 10. Both are filled
    from the per-row termination step in one place.
    """

    def __init__(self, B, horizon, device):
        self.B, self.H, self.device = B, horizon, device
        self.actions = torch.zeros(B, horizon, dtype=torch.long, device=device)
        self.rewards = torch.zeros(B, horizon, device=device)
        self.done = np.zeros(B, bool)
        self.term_at = np.full(B, -1)
        self.n_states = np.full(B, horizon + 1)

    def terminate(self, t, is_terminal):
        """Mark the rows whose frame ``t`` the reward head calls terminal."""
        newly = (~self.done) & np.asarray(is_terminal, bool)
        self.term_at[newly] = t
        self.n_states[newly] = t + 1
        self.done |= newly
        return newly

    def finish(self, extra):
        cont = torch.ones(self.B, self.H + 1, device=self.device)
        alive = torch.zeros(self.B, self.H + 1, device=self.device)
        for i in range(self.B):
            if self.term_at[i] >= 0:
                cont[i, self.term_at[i]:] = 0.0
                alive[i, :self.term_at[i] + 1] = 1.0
            else:
                alive[i, :self.n_states[i]] = 1.0
                cont[i, self.n_states[i]:] = 0.0
        term = self.term_at >= 0
        return {"actions": self.actions, "rewards": self.rewards,
                "continues": cont, "alive": alive,
                "terminated": torch.as_tensor(term, device=self.device),
                "success": float(term.mean()), **extra}


class Imagination:
    """The agent heads on top of the frozen world model: rollout, scoring, losses, checkpoints.

    The rollout runs the world model without gradients and keeps the agent embeddings ``h_t`` it
    produced; the update re-runs ONLY the heads over that buffer. Because the transformer is frozen
    this is exact.
    """

    def __init__(self, world, heads, ckpt, cfg, device):
        self.world, self.heads, self.cfg, self.device = world, heads, cfg, device
        self.clip_T = int(ckpt["clip_T"])
        self.d_in = heads.d_in
        self.bins = heads.reward.twohot.bin_values.detach().to(device)
        self.term_bin = terminal_bins(heads.reward, world.continues_from_reward, device)
        self.prior = copy.deepcopy(heads.policy).eval()
        for p in self.prior.parameters():
            p.requires_grad_(False)
        # Only the policy and the value head move (Section 3.3). The agent-token encoder is an
        # INPUT to the frozen transformer, so its gradient would have to travel back through a
        # forward this phase never repeats -- it is frozen with the rest of the world model.
        for module in (heads.tokens, heads.reward):
            for p in module.parameters():
                p.requires_grad_(False)
        self.policy_params = list(heads.policy.parameters())
        self.value_params = list(heads.value.parameters())
        self.ckpt = ckpt

    def decode_reward(self, probs):
        """The scalar reward a dream pays, from the reward head's distribution over bins.

        ``mean`` is the expectation over all bins. ``mode`` is the two-hot mean restricted to the
        most likely bin and its two neighbours: a categorical head always leaks a little mass onto
        far bins, and where one rare reward dwarfs the per-step one that leak IS the signal's size
        -- on the gridworld 1 % of mass on the +1 bin pays +0.01, exactly the step cost, and it
        concentrates near the goal (measured in dreams: a wrong move two cells from the goal had a
        HIGHER mean return than the optimal one). A recorded reward is two-hot encoded onto two
        adjacent bins, so the local mean decodes it exactly and ignores the leak.
        """
        if self.cfg.reward_decode == "mean":
            return (probs * self.bins).sum(-1)
        top = probs.argmax(-1, keepdim=True)
        idx = (top + torch.arange(-1, 2, device=probs.device)).clamp(0, probs.shape[-1] - 1)
        local = probs.gather(-1, idx)
        # a clamped index repeats an edge bin; count it once
        local = local * torch.cat([idx[..., :1] != idx[..., 1:2], torch.ones_like(idx[..., :1], dtype=torch.bool),
                                   idx[..., 2:] != idx[..., 1:2]], -1)
        return (local * self.bins[idx]).sum(-1) / local.sum(-1).clamp_min(1e-8)

    def eval_policy(self):
        return AgentPolicy(self.world.dyn, self.heads, window=self.clip_T,
                           tau_ctx=self.world.tau_ctx, k_max=self.world.k_max)

    @torch.no_grad()
    def rollout(self, starts_batch, *, horizon, K, term_prob):
        world, heads, dev = self.world, self.heads, self.device
        B = len(starts_batch["encode"])
        D = world.action_vec_dim
        hist = world.tok.history

        # The recorded context, encoded exactly as phase 2 encoded it.
        z = world.tok.encode_frames(starts_batch["encode"])[:, hist - 1:].float().to(dev)
        prop = torch.as_tensor(starts_batch["proprio"], device=dev)
        act_hist = torch.as_tensor(starts_batch["actions"], device=dev)
        task = torch.as_tensor(starts_batch["task"], device=dev)
        # One KV cache holding ``clip_T - 1`` PAST frames: the frame being committed (or denoised)
        # is the window's last slot, so the policy reads ``clip_T`` slots -- the clips phase 2
        # trained on and the window the evaluator plays with -- and the dynamics denoises against
        # as many past frames as ITS training windows had. A longer cache is not a richer context,
        # it is a broken simulator: the flow head has never seen it. Measured on the empty maze
        # (dynamics trained on 4-frame windows, recorded actions replayed through this loop): up
        # to 5 past frames the dreamed player is in the wrong cell on 0.2 % of the steps, with 7
        # or 11 on 93-94 % -- and that is what `main` refuses below.
        cache = world.dyn.transformer.make_kv_cache()
        cache.max_T = max(1, self.clip_T - 1)

        tape = Tape(B, horizon, dev)
        H = torch.zeros(B, horizon + 1, self.d_in, device=dev)
        t = 0
        for t in range(horizon + 1):
            new = z.shape[1] if t == 0 else 1
            h = dream_context(world, heads, z_hist=z[:, -new:], prop_hist=prop[:, -new:],
                              act_hist=act_hist[:, -new:], tau_ctx=world.tau_ctx,
                              task_ids=task, cache=cache, commit=True)
            H[:, t] = h.float()
            if t > 0:
                # The reward head reads the reward that ARRIVED with this frame, i.e. the reward of
                # the t-1 -> t transition, and the terminal rule on the same distribution says
                # whether this frame ends the episode.
                probs = heads.reward.at(h, 0).float().softmax(-1)
                tape.rewards[:, t - 1] = (self.decode_reward(probs)
                                          * torch.as_tensor(~tape.done, device=dev))
                p_term = (probs * self.term_bin).sum(-1)
                tape.terminate(t, (p_term > term_prob).cpu().numpy())
                if tape.done.all():
                    break
            if t == horizon:
                break
            logits = heads.policy.at(h, 0).float()
            a = torch.distributions.Categorical(logits=logits).sample()
            tape.actions[:, t] = a
            av = torch.zeros(B, 1, D + 1, device=dev)
            av[torch.arange(B), 0, a.clamp(max=D - 1)] = 1.0
            act_hist = torch.cat([act_hist, av], 1)
            z_new, prop_new = dream_step(world, z_hist=z, prop_hist=prop,
                                         act_hist=act_hist[:, -(z.shape[1] + 1):], K=K, cache=cache)
            z = torch.cat([z, z_new[:, None]], 1)
            prop = torch.cat([prop, prop_new[:, None]], 1)
        H[:, t + 1:] = H[:, t:t + 1]                  # freeze the tail of finished episodes
        return tape.finish({"H": H})

    def score(self, roll):
        """Policy logits, the value distribution and its decoded mean -- all with gradients."""
        h = roll["H"]
        logits = self.heads.policy.at(h, 0).float()
        vlogits = self.heads.value.at(h, 0).float()
        return logits, vlogits, self.heads.value.mean(vlogits)

    def value_loss(self, vlogits, targets, alive):
        """Paper Eq. 10: ``- ln p(R^lambda_t | s_t)`` against the two-hot encoding of the return."""
        nll = -self.heads.value.twohot.log_prob(vlogits, targets.detach())
        return (nll * alive).sum() / alive.sum().clamp_min(1.0)

    def prior_logits(self, roll, horizon):
        return self.prior.at(roll["H"][:, :horizon], 0).float()

    def save(self, path, extra):
        torch.save({**{k: v for k, v in self.ckpt.items()
                       if k in ("agent_cfg", "dyn", "n_agent", "clip_T", "dyn_source")},
                    "agent": self.heads.state_dict(), "train_cfg": vars(self.cfg), **extra}, path)


def parse_args():
    ap = argparse.ArgumentParser(description="Dreamer 4 phase 3: PMPO in imagination")
    ap.add_argument("--dyn", required=True,
                    help="phase-1 dynamics checkpoint: it names the dataset and the tokenizer")
    ap.add_argument("--init_from", required=True,
                    help="phase-2 checkpoint: warm start, KL prior and the frozen reward head")
    ap.add_argument("--out", required=True)
    ap.add_argument("--steps", type=int, default=1000)
    ap.add_argument("--batch", type=int, default=256,
                    help="dreams per update; the rollout is latency-bound, 256 costs 10 %% more than 32")
    ap.add_argument("--horizon", type=int, default=0,
                    help="imagined steps per dream; 0 = the longest recorded episode")
    ap.add_argument("--K", type=int, default=1, help="shortcut denoising steps per imagined frame")
    ap.add_argument("--term_prob", type=float, default=0.5,
                    help="end a dream when the reward head puts this much mass on a terminal reward")
    ap.add_argument("--reward_decode", choices=("mean", "mode"), default="mode",
                    help="how a dream turns the reward head's distribution into a number: the "
                         "expectation over all bins, or ('mode') the two-hot mean around the most "
                         "likely bin, which ignores the mass a categorical head leaks onto far bins. "
                         "NOT in the paper; with 'mean' the gridworld recipe ends at 0.95-0.98 "
                         "success instead of 1.000 (1 %% of leaked mass on the +1 bin pays the whole "
                         "step cost). Use 'mean' where rewards are genuinely stochastic")
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--value_lr", type=float, default=1e-3)
    ap.add_argument("--lr_final", type=float, default=1e-4, help="both rates decay linearly to this")
    ap.add_argument("--grad_clip", type=float, default=0.5)
    ap.add_argument("--gamma", type=float, default=0.997, help="paper Eq. 10")
    ap.add_argument("--lam", type=float, default=0.95,
                    help="lambda of the lambda-return; the paper defines it but gives no value")
    ap.add_argument("--value_weight", type=float, default=0.5)
    ap.add_argument("--alpha", type=float, default=0.5, help="paper Eq. 11")
    ap.add_argument("--beta", type=float, default=0.03,
                    help="weight of the reverse KL to the behavioral prior (paper Eq. 11; the paper "
                         "uses 0.3, which holds the policy to a weak cloned prior)")
    ap.add_argument("--adv_drop_frac", type=float, default=0.1,
                    help="NOT in the paper: drop this fraction of each PMPO pool, smallest |advantage| "
                         "first, so coin-flip advantages do not vote (0 with --adv_drop_final -1 = "
                         "the paper's pure sign split)")
    ap.add_argument("--adv_drop_final", type=float, default=0.9,
                    help="ramp the dropped fraction linearly to this value over --adv_drop_steps "
                         "updates; negative = keep --adv_drop_frac throughout. 0.5-0.9 measured "
                         "alike; it needs a sharp critic (--n_agent >= 4), with a blunt one it hurts")
    ap.add_argument("--adv_drop_steps", type=int, default=300)
    ap.add_argument("--eval_every", type=int, default=1000)
    ap.add_argument("--eval_n", type=int, default=1000)
    ap.add_argument("--eval_seed", type=int, default=31337,
                    help="episode seeds for the real-env evaluation: held-out layouts")
    ap.add_argument("--eval_envs", type=int, default=64, help="envs played in parallel")
    ap.add_argument("--log_every", type=int, default=50)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--amp", type=int, default=1, help="bf16 autocast (no grad scaler needed)")
    ap.add_argument("--compile", type=int, default=1,
                    help="torch.compile the dynamics model: 0.57 -> 0.33 s per update for ~30 s of warm-up")
    return ap.parse_args()


def load_agent(cfg, dev):
    """Open the phase-2 (or phase-3) checkpoint and rebuild the world model and heads from it."""
    ckpt = torch.load(cfg.init_from, map_location="cpu", weights_only=False)
    world = WorldModel(cfg.dyn, device=cfg.device, n_agent=int(ckpt["n_agent"]))
    # The transformer phase 2 finetuned IS the world model from here on.
    world.load_dynamics_weights(ckpt["dyn"])
    world.dyn.eval()
    heads = build_agent_heads(ckpt["agent_cfg"]).to(dev)
    heads.load_state_dict(ckpt["agent"])
    return world, Imagination(world, heads, ckpt, cfg, dev)


def main():
    cfg = parse_args()
    torch.manual_seed(cfg.seed)
    np.random.seed(cfg.seed)
    torch.set_float32_matmul_precision("high")             # tf32 matmuls
    dev = torch.device(cfg.device)
    out = Path(cfg.out)
    (out / "checkpoints").mkdir(parents=True, exist_ok=True)

    world, agent = load_agent(cfg, dev)
    if agent.clip_T > world.window:
        raise ValueError(
            f"this phase-2 checkpoint reads a {agent.clip_T}-slot context, but the dynamics model "
            f"was trained on {world.window}-frame windows: dreamed with {agent.clip_T - 1} past "
            f"frames it stops following the actions (the player lands in the wrong cell on >90 % "
            f"of the steps), so the policy would be optimised inside a broken simulator. Rerun "
            f"phase 2 with --clip_T <= {world.window}, or train phase 1b with a longer "
            f"--data.seq_len.")
    if cfg.horizon <= 0:
        longest = max(world.dataset.episode_frames(i) for i in range(len(world.dataset))) - 1
        cfg.horizon = longest if longest > 0 else 40
    json.dump({**vars(cfg), "data": world.data_path}, open(out / "config.json", "w"), indent=1)
    if cfg.compile:
        world.dyn = torch.compile(world.dyn, dynamic=True)
    print(f"warm start + KL prior from {cfg.init_from}", flush=True)

    opt = torch.optim.AdamW([{"params": agent.policy_params, "lr": cfg.lr},
                             {"params": agent.value_params, "lr": cfg.value_lr}], weight_decay=0.0)
    base_lrs = [cfg.lr, cfg.value_lr]

    rng = np.random.default_rng(cfg.seed)
    starts = DemoStarts(world.dataset, window=agent.clip_T, history=world.tok.history, rng=rng)
    print(f"dream starts: {len(starts.index)} contexts of {agent.clip_T} frames from "
          f"{world.data_path} | horizon {cfg.horizon}", flush=True)
    eval_envs = [make_env(world.env_spec) for _ in range(cfg.eval_envs)] if world.env_spec else []
    if not eval_envs:
        print("no env_spec in this dataset: real-env evaluation is skipped and no best.pt is "
              "written", flush=True)
    eval_policy = agent.eval_policy()
    # A rerun into the same --out replaces everything: the metrics file is truncated and
    # TensorBoard purges from step 0, so the two never disagree about which run they describe.
    mf = open(out / "metrics.jsonl", "w", buffering=1)
    writer = SummaryWriter(str(out / "tb"), purge_step=0)
    tb_names = {"dream_success": "dream/success_rate", "value_loss": "critic/value_loss",
                "grad_norm": "train/grad_norm", "entropy": "policy/entropy",
                "kl_to_prior": "policy/kl_to_bc_prior", "pos_frac": "pmpo/positive_adv_frac",
                "dreams": "dream/imagined_episodes", "it_s": "train/steps_per_sec_cumulative"}
    t_last = s_last = None

    B, H = cfg.batch, cfg.horizon
    # best starts BELOW every reachable success rate, so a policy that never succeeds still writes
    # best.pt and the script's resume check cannot mark the phase done with a missing artifact.
    collected, best = 0, -1.0
    last_eval, best_eval = {}, {}
    t0 = time.time()
    for step in range(cfg.steps):
        do_log = step % cfg.log_every == 0
        frac = step / max(1, cfg.steps - 1)
        for group, lr0 in zip(opt.param_groups, base_lrs):
            group["lr"] = lr0 * (1.0 - frac) + cfg.lr_final * frac

        # On-policy: one fresh batch of dreams per update.
        with torch.autocast("cuda", torch.bfloat16, enabled=bool(cfg.amp)):
            roll = agent.rollout(starts.sample(B), horizon=H, K=cfg.K, term_prob=cfg.term_prob)
        collected += 1

        alive = roll["alive"]
        with torch.autocast("cuda", torch.bfloat16, enabled=bool(cfg.amp)):
            lg, vlogits, v = agent.score(roll)
        rewards_in = torch.cat([roll["rewards"], torch.zeros_like(roll["rewards"][:, :1])], 1)
        gates_in = torch.cat([roll["continues"][:, 1:], torch.ones_like(roll["continues"][:, :1])], 1)
        targets = compute_lambda_returns(rewards_in, v.detach(), gates_in, gamma=cfg.gamma,
                                         lam=cfg.lam)
        value_loss = agent.value_loss(vlogits, targets, alive)

        # PMPO (Eq. 11): sign-of-advantage policy term plus the reverse KL to the frozen prior.
        adv = targets[:, :H] - v.detach()[:, :H]
        # States the policy really ACTED from. The frame a dream ends on is occupied (its value,
        # zero, is a legitimate critic target) but nothing is done from it: the action the rollout
        # samples there is never executed, and its advantage is just -v(terminal). Eq. 11 only uses
        # the SIGN of the advantage, so that one junk transition per finished dream would push a
        # real action up or down at full weight -- in features that sit next to those of the
        # states adjacent to the goal, which is where the damage showed (greedy success 1.000 ->
        # 0.988 on the empty maze, every failure a loop one or two cells from the goal).
        keep = (alive[:, :H] > 0) & (roll["continues"][:, :H] > 0)
        drop = cfg.adv_drop_frac
        if cfg.adv_drop_final >= 0:
            drop += (cfg.adv_drop_final - drop) * min(1.0, step / max(1, cfg.adv_drop_steps))
        coeff, pinfo = pmpo_coeffs(adv[keep], alpha=cfg.alpha, drop_frac=drop)
        dist = torch.distributions.Categorical(logits=lg[:, :H])
        lp = dist.log_prob(roll["actions"])[keep]
        with torch.no_grad():
            plg = agent.prior_logits(roll, H)
        kl = torch.distributions.kl_divergence(dist, torch.distributions.Categorical(logits=plg))[keep]
        loss = cfg.value_weight * value_loss + (coeff * lp).sum() + cfg.beta * kl.mean()

        opt.zero_grad(set_to_none=True)
        loss.backward()
        gn = torch.nn.utils.clip_grad_norm_(agent.policy_params + agent.value_params, cfg.grad_clip)
        opt.step()

        if do_log:
            pinfo["entropy"] = float(dist.entropy()[keep].mean().detach())
            pinfo["kl_to_prior"] = float(kl.mean().detach())
            rec = {"step": step, "dreams": collected * B, "wall_s": round(time.time() - t0, 1),
                   "dream_success": roll["success"], "value_loss": value_loss.item(),
                   "grad_norm": float(gn), "it_s": (step + 1) / max(time.time() - t0, 1e-9),
                   **{k: float(x) for k, x in pinfo.items()}}
            mf.write(json.dumps(rec) + "\n")
            for k, x in rec.items():
                if k not in ("step", "wall_s"):
                    writer.add_scalar(tb_names.get(k, f"pmpo/{k}"), float(x), step)
            # it_s above is (step+1)/elapsed -- cumulative, so it cannot show a slowdown
            now = time.time()
            if t_last is not None and now > t_last:
                writer.add_scalar("train/steps_per_sec_inst", (step - s_last) / (now - t_last), step)
            t_last, s_last = now, step
            print(f"[{time.strftime('%H:%M:%S')}] step {step}/{cfg.steps} "
                  f"dreamSR {roll['success']:.2f} vloss {rec['value_loss']:.4f} "
                  f"H {pinfo['entropy']:.2f} kl {pinfo['kl_to_prior']:.3f} "
                  f"gn {float(gn):.1f} {rec['it_s']:.2f}it/s", flush=True)

        if eval_envs and ((step + 1) % cfg.eval_every == 0 or step == cfg.steps - 1):
            kw = dict(tok=world.tok, proprio_from_info=world.proprio_from_info, n=cfg.eval_n,
                      seed=cfg.eval_seed, device=dev)
            g = evaluate(eval_policy, eval_envs, greedy=True, **kw)
            s = evaluate(eval_policy, eval_envs, greedy=False, **kw)
            last_eval = {"step": step + 1, "dreams": collected * B, "greedy": g[0], "sampled": s[0],
                         "greedy_opt": g[2], "sampled_opt": s[2], "eval_n": cfg.eval_n}
            print(f"PMPO-EVAL {out.name} step {step + 1} dreams {collected * B} "
                  f"greedy SR {g[0]:.4f} opt {g[2]:.4f} | sampled SR {s[0]:.4f} opt {s[2]:.4f} "
                  f"| n={cfg.eval_n} | {(time.time() - t0) / 60:.1f} min", flush=True)
            for k, x in (("greedy_sr", g[0]), ("greedy_opt", g[2]),
                         ("sampled_sr", s[0]), ("sampled_opt", s[2])):
                writer.add_scalar(f"eval/{k}", x, step + 1)
            writer.flush()
            agent.save(out / "checkpoints" / "latest.pt", last_eval)
            # best.pt: the highest greedy success rate, ties broken by the shorter path -- the first
            # checkpoint to reach 100 % is rarely the best one (phase 2 selects the same way)
            if (g[0], -g[2]) > (best, -best_eval.get("greedy_opt", float("inf"))):
                best = g[0]
                best_eval = last_eval
                agent.save(out / "checkpoints" / "best.pt", last_eval)

    wall = time.time() - t0
    json.dump({"steps": cfg.steps, "wall_s": round(wall, 1), "dreams": collected * B,
               "best_greedy_sr": best, "best": best_eval, "final": last_eval},
              open(out / "final.json", "w"), indent=1)
    print(f"PMPO-DONE {out.name} best greedy SR {best:.4f} | {wall / 60:.2f} min", flush=True)
    mf.close()
    writer.close()


if __name__ == "__main__":
    main()
